/**
 * Public surface for the renderer-wide preferences concern: persisted user
 * preference atoms (theme, fonts, sounds, follow-up behavior, composer model
 * memory) plus the theme-application side-effect hook.
 *
 * Outside this folder, import from `@/renderer/state/preferences` only.
 */
export type {
	AccessibleColorVariant,
	BranchPrefixSource,
	ChatModeDefault,
	CodeTheme,
	CompletionSound,
	FollowUpBehavior,
	MarkdownStyle,
	PiPersonality,
	RepoActionKey,
	RepoSettingsKey,
	RepoSettingsOverride,
	SendShortcut,
	ThemeMode,
	ToolCallCollapseMode,
} from './atoms';
export {
	accessibleColorsAtom,
	alwaysShowContextUsageAtom,
	archiveOnMergeAtom,
	autoConvertLongTextAtom,
	autoRunAfterSetupAtom,
	branchPrefixCustomAtom,
	branchPrefixSourceAtom,
	caffeinateWhileRunningAtom,
	codeLigaturesAtom,
	codeThemeAtom,
	coloredSidebarDiffsAtom,
	completionSoundAtom,
	customPiExecutablePathAtom,
	defaultChatModeAtom,
	defaultChatModelAtom,
	defaultChatThinkingLevelAtom,
	deleteBranchOnArchiveAtom,
	desktopNotificationsAtom,
	followUpBehaviorAtom,
	inAppBrowserPreviewAtom,
	lastSelectedPiModelAtom,
	lastSelectedPiThinkingLevelAtom,
	markdownStyleAtom,
	monoFontAtom,
	piPersonalityAtom,
	REPO_ACTION_KEYS,
	REPO_SETTINGS_KEYS,
	renameWorkspaceOnBranchAtom,
	repoSettingsOverrideAtomFamily,
	reviewModelAtom,
	reviewThinkingLevelAtom,
	sendShortcutAtom,
	setUpstreamOnPushAtom,
	showDashboardAtom,
	showMcpStatusInChatAtom,
	showSidebarResourceUsageAtom,
	sidebarChatsModeAtom,
	softenCertaintyAtom,
	terminalFontAtom,
	terminalFontSizeAtom,
	terminalScrollbackMbAtom,
	themeAtom,
	toolCallCollapseAtom,
} from './atoms';
export { useThemeEffect } from './use-theme-effect';
