import {
	ActivityIcon,
	BadgeCheckIcon,
	BlocksIcon,
	BookOpenIcon,
	BoxIcon,
	BugIcon,
	CalculatorIcon,
	CloudIcon,
	CodeIcon,
	CogIcon,
	ComponentIcon,
	ContainerIcon,
	CpuIcon,
	DatabaseIcon,
	DownloadIcon,
	EyeIcon,
	FileCodeIcon,
	FlameIcon,
	FlaskConicalIcon,
	FolderIcon,
	GaugeIcon,
	GitBranchIcon,
	GitMergeIcon,
	GitPullRequestIcon,
	GlobeIcon,
	HammerIcon,
	HardDriveIcon,
	KeyIcon,
	LayersIcon,
	LayoutDashboardIcon,
	ListChecksIcon,
	LockIcon,
	type LucideIcon,
	MicroscopeIcon,
	MonitorIcon,
	NetworkIcon,
	PackageIcon,
	PaintbrushIcon,
	PaletteIcon,
	PlayIcon,
	PlugIcon,
	RefreshCwIcon,
	RepeatIcon,
	RocketIcon,
	SearchIcon,
	SendIcon,
	ServerIcon,
	SettingsIcon,
	ShieldCheckIcon,
	SmartphoneIcon,
	SparklesIcon,
	TerminalIcon,
	TestTubeIcon,
	TimerIcon,
	TrendingUpIcon,
	UploadIcon,
	WrenchIcon,
	ZapIcon,
} from 'lucide-react';

import {
	DEFAULT_RUN_SCRIPT_ICON,
	type RunScriptIconName,
} from '@/shared/scripts';

/**
 * Every curated run-script icon name mapped to its lucide component. The
 * exhaustive `Record` is the point: adding a name to `RUN_SCRIPT_ICON_NAMES`
 * without a component here fails the type-check instead of rendering nothing.
 */
const RUN_SCRIPT_ICONS: Record<RunScriptIconName, LucideIcon> = {
	activity: ActivityIcon,
	'badge-check': BadgeCheckIcon,
	blocks: BlocksIcon,
	'book-open': BookOpenIcon,
	box: BoxIcon,
	bug: BugIcon,
	calculator: CalculatorIcon,
	cloud: CloudIcon,
	code: CodeIcon,
	cog: CogIcon,
	component: ComponentIcon,
	container: ContainerIcon,
	cpu: CpuIcon,
	database: DatabaseIcon,
	download: DownloadIcon,
	eye: EyeIcon,
	'file-code': FileCodeIcon,
	flame: FlameIcon,
	'flask-conical': FlaskConicalIcon,
	folder: FolderIcon,
	gauge: GaugeIcon,
	'git-branch': GitBranchIcon,
	'git-merge': GitMergeIcon,
	'git-pull-request': GitPullRequestIcon,
	globe: GlobeIcon,
	hammer: HammerIcon,
	'hard-drive': HardDriveIcon,
	key: KeyIcon,
	layers: LayersIcon,
	'layout-dashboard': LayoutDashboardIcon,
	'list-checks': ListChecksIcon,
	lock: LockIcon,
	microscope: MicroscopeIcon,
	monitor: MonitorIcon,
	network: NetworkIcon,
	package: PackageIcon,
	paintbrush: PaintbrushIcon,
	palette: PaletteIcon,
	play: PlayIcon,
	plug: PlugIcon,
	'refresh-cw': RefreshCwIcon,
	repeat: RepeatIcon,
	rocket: RocketIcon,
	search: SearchIcon,
	send: SendIcon,
	server: ServerIcon,
	settings: SettingsIcon,
	'shield-check': ShieldCheckIcon,
	smartphone: SmartphoneIcon,
	sparkles: SparklesIcon,
	terminal: TerminalIcon,
	'test-tube': TestTubeIcon,
	timer: TimerIcon,
	'trending-up': TrendingUpIcon,
	upload: UploadIcon,
	wrench: WrenchIcon,
	zap: ZapIcon,
};

/**
 * Renders a run script's configured icon at the surrounding icon size, falling
 * back to the default icon so a name outside the curated set still renders.
 */
export function RunScriptIcon({
	className,
	name,
	...props
}: { name: RunScriptIconName } & React.ComponentProps<LucideIcon>) {
	const Icon =
		RUN_SCRIPT_ICONS[name] ?? RUN_SCRIPT_ICONS[DEFAULT_RUN_SCRIPT_ICON];

	return <Icon aria-hidden='true' className={className} {...props} />;
}
