import { describe, expect, test } from 'vitest';

import { splitMarkdownFrontmatter } from '../../src/renderer/lib/markdown-frontmatter';

describe('splitMarkdownFrontmatter', () => {
	test('lifts a flat block off the body', () => {
		const result = splitMarkdownFrontmatter(
			'---\ntitle: Release notes\nstatus: draft\n---\n\n# Release notes\n',
		);

		expect(result.frontmatter).toEqual({
			entries: [
				{ key: 'title', value: 'Release notes' },
				{ key: 'status', value: 'draft' },
			],
			kind: 'entries',
		});
		expect(result.body).toBe('# Release notes\n');
	});

	test('drops the quotes a scalar was written with', () => {
		const result = splitMarkdownFrontmatter(
			'---\nchatTabId: "d2610d0b-8660-4f58-9fa7-faf3527e7e1c"\n---\nBody.',
		);

		expect(result.frontmatter).toEqual({
			entries: [
				{ key: 'chatTabId', value: 'd2610d0b-8660-4f58-9fa7-faf3527e7e1c' },
			],
			kind: 'entries',
		});
	});

	test('reads a list written beneath its key back as one line', () => {
		const result = splitMarkdownFrontmatter(
			'---\ntags:\n  - agents\n  - review\nowner: philipp\n---\nBody.',
		);

		expect(result.frontmatter).toEqual({
			entries: [
				{ key: 'tags', value: 'agents, review' },
				{ key: 'owner', value: 'philipp' },
			],
			kind: 'entries',
		});
	});

	test('keeps a key whose value is empty', () => {
		const result = splitMarkdownFrontmatter('---\nassignee:\n---\nBody.');

		expect(result.frontmatter).toEqual({
			entries: [{ key: 'assignee', value: '' }],
			kind: 'entries',
		});
	});

	test('shows a nested block as written rather than guessing at it', () => {
		const result = splitMarkdownFrontmatter(
			'---\nauthor:\n  name: Philipp\n  email: philipp@example.com\n---\nBody.',
		);

		expect(result.frontmatter).toEqual({
			kind: 'raw',
			text: 'author:\n  name: Philipp\n  email: philipp@example.com',
		});
		expect(result.body).toBe('Body.');
	});

	test('closes on a document-end marker as well as a fence', () => {
		const result = splitMarkdownFrontmatter('---\ntitle: Notes\n...\nBody.');

		expect(result.frontmatter).toEqual({
			entries: [{ key: 'title', value: 'Notes' }],
			kind: 'entries',
		});
		expect(result.body).toBe('Body.');
	});

	test('strips an empty block without drawing a header for it', () => {
		const result = splitMarkdownFrontmatter('---\n---\n\n# Notes\n');

		expect(result.frontmatter).toBeNull();
		expect(result.body).toBe('# Notes\n');
	});

	test('reads a block written with CRLF line endings', () => {
		const result = splitMarkdownFrontmatter(
			'---\r\ntitle: Notes\r\n---\r\n\r\n# Notes\r\n',
		);

		expect(result.frontmatter).toEqual({
			entries: [{ key: 'title', value: 'Notes' }],
			kind: 'entries',
		});
		expect(result.body).toBe('# Notes\n');
	});

	test('leaves a document that opens with a thematic break alone', () => {
		const source = '---\n\nA horizontal rule, not frontmatter.\n';
		const result = splitMarkdownFrontmatter(source);

		expect(result.frontmatter).toBeNull();
		expect(result.body).toBe(source);
	});

	test('leaves a body-level rule alone', () => {
		const source = '# Notes\n\nBody copy.\n\n---\n\nMore copy.\n';
		const result = splitMarkdownFrontmatter(source);

		expect(result.frontmatter).toBeNull();
		expect(result.body).toBe(source);
	});

	test('leaves a rule the document closes with a second rule alone', () => {
		const source = '---\n\nIntro paragraph.\n\n---\n\nMore copy.\n';
		const result = splitMarkdownFrontmatter(source);

		expect(result.frontmatter).toBeNull();
		expect(result.body).toBe(source);
	});

	test('leaves a rule wrapping a heading alone', () => {
		const source =
			'---\n# Workspace freeze\n\nBody copy.\n\n---\n\nMore copy.\n';
		const result = splitMarkdownFrontmatter(source);

		expect(result.frontmatter).toBeNull();
		expect(result.body).toBe(source);
	});

	test('leaves a heading fenced by two rules alone', () => {
		const source = '---\n# Workspace freeze\n---\n\nBody copy.\n';
		const result = splitMarkdownFrontmatter(source);

		expect(result.frontmatter).toBeNull();
		expect(result.body).toBe(source);
	});

	test('skips a comment written between two keys', () => {
		const result = splitMarkdownFrontmatter(
			'---\ntitle: Notes\n# written by the summary writer\nowner: philipp\n---\nBody.',
		);

		expect(result.frontmatter).toEqual({
			entries: [
				{ key: 'title', value: 'Notes' },
				{ key: 'owner', value: 'philipp' },
			],
			kind: 'entries',
		});
	});

	test('skips a comment the block opens with when the rest is all keys', () => {
		const result = splitMarkdownFrontmatter(
			'---\n# generated by ensemblr\ntitle: Notes\n---\nBody.',
		);

		expect(result.frontmatter).toEqual({
			entries: [{ key: 'title', value: 'Notes' }],
			kind: 'entries',
		});
	});

	test('shows a block scalar as written rather than folding it', () => {
		const result = splitMarkdownFrontmatter(
			'---\ndescription: |\n  line one\n  line two\n---\nBody.',
		);

		expect(result.frontmatter).toEqual({
			kind: 'raw',
			text: 'description: |\n  line one\n  line two',
		});
	});

	test('shows a block that repeats a key as written rather than picking one', () => {
		const result = splitMarkdownFrontmatter('---\ntag: a\ntag: b\n---\nBody.');

		expect(result.frontmatter).toEqual({
			kind: 'raw',
			text: 'tag: a\ntag: b',
		});
	});

	test('decodes the escapes a double-quoted scalar was written with', () => {
		const result = splitMarkdownFrontmatter(
			`---\ntitle: ${JSON.stringify('Fix the "auth" redirect bug')}\npath: ${JSON.stringify('C:\\notes\\a.md')}\n---\nBody.`,
		);

		expect(result.frontmatter).toEqual({
			entries: [
				{ key: 'title', value: 'Fix the "auth" redirect bug' },
				{ key: 'path', value: 'C:\\notes\\a.md' },
			],
			kind: 'entries',
		});
	});

	test('decodes the doubled quote a single-quoted scalar escapes with', () => {
		const result = splitMarkdownFrontmatter(
			"---\ntitle: 'it''s a draft'\n---\nBody.",
		);

		expect(result.frontmatter).toEqual({
			entries: [{ key: 'title', value: "it's a draft" }],
			kind: 'entries',
		});
	});

	test('leaves a scalar that merely ends in a quote as written', () => {
		const result = splitMarkdownFrontmatter(
			'---\ntitle: "a" and "b"\nnote: \'x\' and \'y\'\n---\nBody.',
		);

		expect(result.frontmatter).toEqual({
			entries: [
				{ key: 'title', value: '"a" and "b"' },
				{ key: 'note', value: "'x' and 'y'" },
			],
			kind: 'entries',
		});
	});
});
