import { fileURLToPath } from 'node:url';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

/**
 * Vitest configuration for the renderer and shared test suites.
 *
 * The default environment is `node` so platform-sensitive pure-logic tests
 * (keymap, etc.) keep the real `navigator`/`process`. DOM component tests opt
 * into happy-dom per file with a `// @vitest-environment happy-dom` docblock.
 * Coverage uses the Istanbul provider and emits `coverage/coverage-final.json`,
 * which `fallow audit --coverage` reads directly. Most of `tests/main` runs on
 * `electron --test`; the pure-logic main-process suites that only need the
 * `node` env are wired in one-by-one below (not a `tests/main/**` glob, which
 * would drag in the electron-only suites).
 *
 * `electron` is aliased to a stub because several of those suites reach
 * `src/main/agent-control/main-integration.ts` through the concern's barrel.
 * Outside an Electron process the real module downloads the packaged binary on
 * import, which made a hermetic unit test depend on a ~100 MB network fetch. A
 * suite that needs Electron behaviour still mocks the module itself.
 */
export default defineConfig({
	plugins: [react()],
	resolve: {
		alias: {
			'@': fileURLToPath(new URL('./src', import.meta.url)),
			electron: fileURLToPath(
				new URL('./tests/main/support/electron-stub.ts', import.meta.url),
			),
		},
	},
	test: {
		globals: true,
		environment: 'node',
		setupFiles: ['./tests/renderer/support/vitest.setup.ts'],
		include: [
			'tests/renderer/**/*.test.{ts,tsx}',
			'tests/shared/**/*.test.ts',
			'tests/scripts/**/*.test.mjs',
			'tests/main/agent-skill-bundle.test.ts',
			'tests/main/branch-name-slug.test.ts',
			'tests/main/dictation-service.test.ts',
			'tests/main/pi-wire-content-blocks.test.ts',
			'tests/main/sanitize-title.test.ts',
			'tests/main/title-provenance.test.ts',
			'tests/main/derive-title-source.test.ts',
			'tests/main/linked-directory-recents.test.ts',
			'tests/main/linked-directory-service.test.ts',
			'tests/main/apply-branch-slug.test.ts',
			'tests/main/provisional-branch-slug.test.ts',
			'tests/main/provisional-workspace-naming.test.ts',
			'tests/main/agent-summary.test.ts',
			'tests/main/session-brief-naming.test.ts',
			'tests/main/session-naming.test.ts',
			'tests/main/session-summary-writer.test.ts',
			'tests/main/launch-env.test.ts',
			'tests/main/release-feed.test.ts',
			'tests/main/update-preconditions.test.ts',
			'tests/main/update-service.test.ts',
			'tests/main/infisical-api.test.ts',
			'tests/main/infisical-service.test.ts',
			'tests/main/infisical-cache.test.ts',
			'tests/main/environment-infisical-layer.test.ts',
			'tests/main/executable-discovery.test.ts',
			'tests/main/harness-detection-service.test.ts',
			'tests/main/agent-conversation-title.test.ts',
			'tests/main/request-schemas.test.ts',
			'tests/main/validate-git-ref.test.ts',
			'tests/main/worktree-placement.test.ts',
			'tests/main/external-links-policy.test.ts',
			'tests/main/media-permissions-policy.test.ts',
			'tests/main/app-settings-service.test.ts',
			'tests/main/published-schemas.test.ts',
			'tests/main/menu-build.test.ts',
			'tests/main/menu-strings.test.ts',
			'tests/main/open-in-editor.test.ts',
			'tests/main/workspace-scripts-handler.test.ts',
			'tests/main/workspace-files-watcher.test.ts',
			'tests/main/agent-activity-monitor.test.ts',
			'tests/main/notification-target.test.ts',
			'tests/main/notification-strings.test.ts',
			'tests/main/notification-retention.test.ts',
			'tests/main/electron-notify.test.ts',
			'tests/main/quit-guard.test.ts',
			'tests/main/quit-guard-strings.test.ts',
			'tests/main/linear-callback-page-strings.test.ts',
			'tests/main/quit-coordinator.test.ts',
			'tests/main/macos-battery.test.ts',
			'tests/main/workspace-commits.test.ts',
			'tests/main/list-workspace-files.test.ts',
			'tests/main/open-target-paths.test.ts',
			'tests/main/workspace-pr-sweeper.test.ts',
			'tests/main/terminal-scrollback-text.test.ts',
			'tests/main/agent-control-service.test.ts',
			'tests/main/agent-control-guardrails.test.ts',
			'tests/main/agent-control-origin-registry.test.ts',
			'tests/main/agent-control-control-server.test.ts',
			'tests/main/agent-control-mcp-endpoint.test.ts',
			'tests/main/agent-control-port-adapters.test.ts',
			'tests/main/agent-control-review-ports.test.ts',
			'tests/main/agent-control-linear-ports.test.ts',
			'tests/main/agent-control-workspace-linked-issue.test.ts',
			'tests/main/agent-control-harness-launch-config.test.ts',
			'tests/main/agent-control-harness-playbook-file.test.ts',
			'tests/main/agent-control-model-resolution.test.ts',
			'tests/main/agent-control-wait.test.ts',
			'tests/main/agent-control-awareness-parity.test.ts',
			'tests/main/agent-control-arg-naming.test.ts',
			'tests/main/agent-control-doc-parity.test.ts',
			'tests/main/agent-control-timeline-labels.test.ts',
			'tests/main/agent-control-session-naming.test.ts',
			'tests/main/agent-control-ask-user-question.test.ts',
			'tests/main/board-status-store.test.ts',
			'tests/main/plan-mode-registry.test.ts',
			'tests/main/plan-mode-submission.test.ts',
			'tests/main/plan-mode-plan-file-writer.test.ts',
			'tests/main/plan-mode-control-gate.test.ts',
			'tests/main/plan-mode-spawn-inheritance.test.ts',
			'tests/main/plan-mode-op-policy.test.ts',
			'tests/main/agent-control-env-role.test.ts',
			'tests/main/agent-provider-handlers.test.ts',
			'tests/main/claude-readiness.test.ts',
			'tests/main/claude-subagent-mode.test.ts',
			'tests/main/claude-agent-control-wiring.test.ts',
			'tests/main/claude-plan-bridge.test.ts',
			'tests/main/claude-plan-mode-persistence.test.ts',
			'tests/main/claude-session-continuity.test.ts',
			'tests/main/claude-session-permission-mode.test.ts',
			'tests/main/claude-tool-approval.test.ts',
			'tests/main/claude-executable-plumbing.test.ts',
			'tests/main/claude-mcp-roster.test.ts',
			'tests/main/claude-slash-commands.test.ts',
			'tests/main/claude-model-catalog.test.ts',
			'tests/main/agent-session-provider-pin.test.ts',
			'tests/main/claude-agent-submit.test.ts',
			'tests/main/claude-context-usage-probe.test.ts',
			'tests/main/claude-turn-preamble.test.ts',
			'tests/main/claude-thinking-display.test.ts',
			'tests/main/claude-usage.test.ts',
			'tests/main/agent-event-payload.test.ts',
			'tests/main/repository-issue-assignees.test.ts',
		],
		coverage: {
			provider: 'istanbul',
			reporter: ['text', 'json'],
			reportsDirectory: 'coverage',
			include: ['src/**/*.{ts,tsx}'],
		},
	},
});
