/**
 * Registry of IPC channel names exchanged between the Electron main process and
 * the renderer. Each value is the wire identifier used by `ipcMain.handle` /
 * `ipcRenderer.invoke`; keys are the camelCase handles used in the preload bridge.
 */
export const IPC_CHANNELS = {
	applyRepositoryConfigMigration: 'ensemble:apply-repository-config-migration',
	archiveRepository: 'ensemble:archive-repository',
	archiveWorkspace: 'ensemble:archive-workspace',
	bindPiSessionToChatTab: 'ensemble:bind-pi-session-to-chat-tab',
	closeChatTab: 'ensemble:close-chat-tab',
	cloneGithubRepositoryPrepare: 'ensemble:clone-github-repository:prepare',
	cloneGithubRepositoryProgress: 'ensemble:clone-github-repository:progress',
	cloneGithubRepositoryStart: 'ensemble:clone-github-repository:start',
	computeTurnDiff: 'ensemble:compute-turn-diff',
	confirmRootDirectoryChange: 'ensemble:confirm-root-directory-change',
	createTerminalSession: 'ensemble:create-terminal-session',
	createWorkspace: 'ensemble:create-workspace',
	deleteArchivedWorkspace: 'ensemble:delete-archived-workspace',
	deleteRepository: 'ensemble:delete-repository',
	deleteWorkspace: 'ensemble:delete-workspace',
	ensureWindowWidth: 'ensemble:ensure-window-width',
	environmentVariables: 'ensemble:environment-variables',
	githubRepositoryList: 'ensemble:github-repository-list',
	health: 'ensemble:health',
	initialShellSnapshot: 'ensemble:initial-shell-snapshot',
	killTerminalSession: 'ensemble:kill-terminal-session',
	listArchivedWorkspaces: 'ensemble:list-archived-workspaces',
	listChatTabs: 'ensemble:list-chat-tabs',
	listClosedChatTabsWithSummary: 'ensemble:list-closed-chat-tabs-with-summary',
	listPiModels: 'ensemble:list-pi-models',
	listTurnCheckpoints: 'ensemble:list-turn-checkpoints',
	listPiSessionEvents: 'ensemble:list-pi-session-events',
	listPiSessions: 'ensemble:list-pi-sessions',
	listPiSlashCommands: 'ensemble:list-pi-slash-commands',
	listTerminalSessions: 'ensemble:list-terminal-sessions',
	listWorkspaceFiles: 'ensemble:list-workspace-files',
	openChatTab: 'ensemble:open-chat-tab',
	openPiSession: 'ensemble:open-pi-session',
	piRawFrame: 'ensemble:pi-raw-frame',
	piSessionEvent: 'ensemble:pi-session-event',
	previewRepositoryConfigMigration:
		'ensemble:preview-repository-config-migration',
	quickStartProject: 'ensemble:quick-start-project',
	readWorkspaceFile: 'ensemble:read-workspace-file',
	registerLocalRepository: 'ensemble:register-local-repository',
	renameWorkspace: 'ensemble:rename-workspace',
	restoreChatTab: 'ensemble:restore-chat-tab',
	restoreCheckpoint: 'ensemble:restore-checkpoint',
	repositoryConfig: 'ensemble:repository-config',
	resizeTerminalSession: 'ensemble:resize-terminal-session',
	repositoryWorkspaceNavigation: 'ensemble:repository-workspace-navigation',
	rootDirectory: 'ensemble:root-directory',
	runWorkspaceScript: 'ensemble:run-workspace-script',
	selectCloneDestination: 'ensemble:select-clone-destination',
	selectLocalRepository: 'ensemble:select-local-repository',
	selectPiExecutable: 'ensemble:select-pi-executable',
	selectRootDirectory: 'ensemble:select-root-directory',
	setupDiagnostics: 'ensemble:setup-diagnostics',
	stopPiSession: 'ensemble:stop-pi-session',
	stopWorkspaceScript: 'ensemble:stop-workspace-script',
	submitPiPrompt: 'ensemble:submit-pi-prompt',
	settingsResolution: 'ensemble:settings-resolution',
	sharedRootAdoption: 'ensemble:shared-root-adoption',
	terminalLifecycle: 'ensemble:terminal-lifecycle',
	terminalOutput: 'ensemble:terminal-output',
	terminalSnapshot: 'ensemble:terminal-snapshot',
	unarchiveWorkspace: 'ensemble:unarchive-workspace',
	writeForkSummary: 'ensemble:write-fork-summary',
	writeTerminalSession: 'ensemble:write-terminal-session',
} as const;
