import {
	BellIcon,
	BicepsFlexedIcon,
	BotIcon,
	BrainIcon,
	CircleStopIcon,
	CircleXIcon,
	ClipboardListIcon,
	CrosshairIcon,
	FileDiffIcon,
	FilePenIcon,
	FilePlusIcon,
	FileTextIcon,
	FolderTreeIcon,
	HourglassIcon,
	ImageIcon,
	KanbanIcon,
	KeyboardIcon,
	ListIcon,
	type LucideIcon,
	MessageCircleQuestionIcon,
	MessageSquareCheckIcon,
	MessageSquarePlusIcon,
	MessageSquareTextIcon,
	PanelsTopLeftIcon,
	PlayIcon,
	PuzzleIcon,
	ScrollTextIcon,
	SearchIcon,
	SendIcon,
	SquareTerminalIcon,
	SquareXIcon,
	StethoscopeIcon,
	TerminalIcon,
	WrenchIcon,
} from 'lucide-react';
import type { ToolGlyph } from '@/renderer/types/tool-presentation';

/**
 * The single icon each glyph key paints, shared by the tool row and the turn
 * summary strip so one tool always reads as the same mark wherever it appears.
 */
export const GLYPH_ICONS: Record<ToolGlyph, LucideIcon> = {
	bell: BellIcon,
	'biceps-flexed': BicepsFlexedIcon,
	bot: BotIcon,
	brain: BrainIcon,
	'circle-stop': CircleStopIcon,
	'circle-x': CircleXIcon,
	'clipboard-list': ClipboardListIcon,
	crosshair: CrosshairIcon,
	'file-diff': FileDiffIcon,
	'file-pen': FilePenIcon,
	'file-plus': FilePlusIcon,
	'file-text': FileTextIcon,
	'folder-tree': FolderTreeIcon,
	hourglass: HourglassIcon,
	image: ImageIcon,
	kanban: KanbanIcon,
	keyboard: KeyboardIcon,
	list: ListIcon,
	'message-circle-question': MessageCircleQuestionIcon,
	'message-square-check': MessageSquareCheckIcon,
	'message-square-plus': MessageSquarePlusIcon,
	'message-square-text': MessageSquareTextIcon,
	'panels-top-left': PanelsTopLeftIcon,
	play: PlayIcon,
	puzzle: PuzzleIcon,
	'scroll-text': ScrollTextIcon,
	search: SearchIcon,
	send: SendIcon,
	'square-terminal': SquareTerminalIcon,
	'square-x': SquareXIcon,
	stethoscope: StethoscopeIcon,
	terminal: TerminalIcon,
	wrench: WrenchIcon,
};
