/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/_workbench'
import { Route as WorkbenchSettingsRouteImport } from './routes/_workbench/settings'
import { Route as WorkbenchShellRouteImport } from './routes/_workbench/_shell'
import { Route as WorkbenchShellIndexRouteImport } from './routes/_workbench/_shell/index'
import { Route as WorkbenchShellHistoryRouteImport } from './routes/_workbench/_shell/history'
import { Route as WorkbenchShellHelpRouteImport } from './routes/_workbench/_shell/help'
import { Route as WorkbenchShellDashboardRouteImport } from './routes/_workbench/_shell/dashboard'
import { Route as WorkbenchShellProjectsProjectIdRouteRouteImport } from './routes/_workbench/_shell/projects/$projectId/route'
import { Route as WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteImport } from './routes/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/route'
import { Route as WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRouteImport } from './routes/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/index'
import { Route as WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRouteImport } from './routes/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/_workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchSettingsRoute = WorkbenchSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchShellRoute = WorkbenchShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchShellIndexRoute = WorkbenchShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkbenchShellRoute,
} as any)
const WorkbenchShellHistoryRoute = WorkbenchShellHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WorkbenchShellRoute,
} as any)
const WorkbenchShellHelpRoute = WorkbenchShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => WorkbenchShellRoute,
} as any)
const WorkbenchShellDashboardRoute = WorkbenchShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkbenchShellRoute,
} as any)
const WorkbenchShellProjectsProjectIdRouteRoute =
  WorkbenchShellProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkbenchShellRoute,
  } as any)
const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute =
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => WorkbenchShellProjectsProjectIdRouteRoute,
  } as any)
const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute =
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute =
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRouteImport.update(
    {
      id: '/chats/$chatId',
      path: '/chats/$chatId',
      getParentRoute: () =>
        WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof WorkbenchShellIndexRoute
  '/settings': typeof WorkbenchSettingsRoute
  '/dashboard': typeof WorkbenchShellDashboardRoute
  '/help': typeof WorkbenchShellHelpRoute
  '/history': typeof WorkbenchShellHistoryRoute
  '/projects/$projectId': typeof WorkbenchShellProjectsProjectIdRouteRouteWithChildren
  '/projects/$projectId/workspaces/$workspaceId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/projects/$projectId/workspaces/$workspaceId/': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute
  '/projects/$projectId/workspaces/$workspaceId/chats/$chatId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkbenchShellIndexRoute
  '/settings': typeof WorkbenchSettingsRoute
  '/dashboard': typeof WorkbenchShellDashboardRoute
  '/help': typeof WorkbenchShellHelpRoute
  '/history': typeof WorkbenchShellHistoryRoute
  '/projects/$projectId': typeof WorkbenchShellProjectsProjectIdRouteRouteWithChildren
  '/projects/$projectId/workspaces/$workspaceId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute
  '/projects/$projectId/workspaces/$workspaceId/chats/$chatId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workbench': typeof WorkbenchRouteWithChildren
  '/_workbench/_shell': typeof WorkbenchShellRouteWithChildren
  '/_workbench/settings': typeof WorkbenchSettingsRoute
  '/_workbench/_shell/dashboard': typeof WorkbenchShellDashboardRoute
  '/_workbench/_shell/help': typeof WorkbenchShellHelpRoute
  '/_workbench/_shell/history': typeof WorkbenchShellHistoryRoute
  '/_workbench/_shell/': typeof WorkbenchShellIndexRoute
  '/_workbench/_shell/projects/$projectId': typeof WorkbenchShellProjectsProjectIdRouteRouteWithChildren
  '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute
  '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/projects/$projectId'
    | '/projects/$projectId/workspaces/$workspaceId'
    | '/projects/$projectId/workspaces/$workspaceId/'
    | '/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/projects/$projectId'
    | '/projects/$projectId/workspaces/$workspaceId'
    | '/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
  id:
    | '__root__'
    | '/_workbench'
    | '/_workbench/_shell'
    | '/_workbench/settings'
    | '/_workbench/_shell/dashboard'
    | '/_workbench/_shell/help'
    | '/_workbench/_shell/history'
    | '/_workbench/_shell/'
    | '/_workbench/_shell/projects/$projectId'
    | '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId'
    | '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/'
    | '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkbenchRoute: typeof WorkbenchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workbench': {
      id: '/_workbench'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workbench/settings': {
      id: '/_workbench/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkbenchSettingsRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/_shell': {
      id: '/_workbench/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchShellRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/_shell/': {
      id: '/_workbench/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchShellIndexRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/_shell/history': {
      id: '/_workbench/_shell/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof WorkbenchShellHistoryRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/_shell/help': {
      id: '/_workbench/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof WorkbenchShellHelpRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/_shell/dashboard': {
      id: '/_workbench/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkbenchShellDashboardRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/_shell/projects/$projectId': {
      id: '/_workbench/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof WorkbenchShellProjectsProjectIdRouteRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId': {
      id: '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof WorkbenchShellProjectsProjectIdRouteRoute
    }
    '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/': {
      id: '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/projects/$projectId/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute
    }
    '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId': {
      id: '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
      preLoaderRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRouteImport
      parentRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute
    }
  }
}

interface WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteChildren {
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute
}

const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteChildren: WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteChildren =
  {
    WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute:
      WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute,
    WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute:
      WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute,
  }

const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren =
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface WorkbenchShellProjectsProjectIdRouteRouteChildren {
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren
}

const WorkbenchShellProjectsProjectIdRouteRouteChildren: WorkbenchShellProjectsProjectIdRouteRouteChildren =
  {
    WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute:
      WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren,
  }

const WorkbenchShellProjectsProjectIdRouteRouteWithChildren =
  WorkbenchShellProjectsProjectIdRouteRoute._addFileChildren(
    WorkbenchShellProjectsProjectIdRouteRouteChildren,
  )

interface WorkbenchShellRouteChildren {
  WorkbenchShellDashboardRoute: typeof WorkbenchShellDashboardRoute
  WorkbenchShellHelpRoute: typeof WorkbenchShellHelpRoute
  WorkbenchShellHistoryRoute: typeof WorkbenchShellHistoryRoute
  WorkbenchShellIndexRoute: typeof WorkbenchShellIndexRoute
  WorkbenchShellProjectsProjectIdRouteRoute: typeof WorkbenchShellProjectsProjectIdRouteRouteWithChildren
}

const WorkbenchShellRouteChildren: WorkbenchShellRouteChildren = {
  WorkbenchShellDashboardRoute: WorkbenchShellDashboardRoute,
  WorkbenchShellHelpRoute: WorkbenchShellHelpRoute,
  WorkbenchShellHistoryRoute: WorkbenchShellHistoryRoute,
  WorkbenchShellIndexRoute: WorkbenchShellIndexRoute,
  WorkbenchShellProjectsProjectIdRouteRoute:
    WorkbenchShellProjectsProjectIdRouteRouteWithChildren,
}

const WorkbenchShellRouteWithChildren = WorkbenchShellRoute._addFileChildren(
  WorkbenchShellRouteChildren,
)

interface WorkbenchRouteChildren {
  WorkbenchShellRoute: typeof WorkbenchShellRouteWithChildren
  WorkbenchSettingsRoute: typeof WorkbenchSettingsRoute
}

const WorkbenchRouteChildren: WorkbenchRouteChildren = {
  WorkbenchShellRoute: WorkbenchShellRouteWithChildren,
  WorkbenchSettingsRoute: WorkbenchSettingsRoute,
}

const WorkbenchRouteWithChildren = WorkbenchRoute._addFileChildren(
  WorkbenchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkbenchRoute: WorkbenchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
