/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/_workbench'
import { Route as DebugPiReplayRouteImport } from './routes/debug.pi-replay'
import { Route as WorkbenchSettingsRouteImport } from './routes/_workbench/settings'
import { Route as WorkbenchShellRouteImport } from './routes/_workbench/_shell'
import { Route as WorkbenchSettingsIndexRouteImport } from './routes/_workbench/settings/index'
import { Route as WorkbenchShellIndexRouteImport } from './routes/_workbench/_shell/index'
import { Route as WorkbenchSettingsProvidersRouteImport } from './routes/_workbench/settings/providers'
import { Route as WorkbenchSettingsModelsRouteImport } from './routes/_workbench/settings/models'
import { Route as WorkbenchSettingsIntegrationsRouteImport } from './routes/_workbench/settings/integrations'
import { Route as WorkbenchSettingsGitRouteImport } from './routes/_workbench/settings/git'
import { Route as WorkbenchSettingsGeneralRouteImport } from './routes/_workbench/settings/general'
import { Route as WorkbenchSettingsExperimentalRouteImport } from './routes/_workbench/settings/experimental'
import { Route as WorkbenchSettingsEnvironmentRouteImport } from './routes/_workbench/settings/environment'
import { Route as WorkbenchSettingsDiagnosticsRouteImport } from './routes/_workbench/settings/diagnostics'
import { Route as WorkbenchSettingsAppearanceRouteImport } from './routes/_workbench/settings/appearance'
import { Route as WorkbenchSettingsAdvancedRouteImport } from './routes/_workbench/settings/advanced'
import { Route as WorkbenchShellHistoryRouteImport } from './routes/_workbench/_shell/history'
import { Route as WorkbenchShellHelpRouteImport } from './routes/_workbench/_shell/help'
import { Route as WorkbenchShellDashboardRouteImport } from './routes/_workbench/_shell/dashboard'
import { Route as WorkbenchSettingsRepoIndexRouteImport } from './routes/_workbench/settings/repo/index'
import { Route as WorkbenchShellLinearIndexRouteImport } from './routes/_workbench/_shell/linear/index'
import { Route as WorkbenchSettingsRepoRepoIdRouteImport } from './routes/_workbench/settings/repo/$repoId'
import { Route as WorkbenchShellLinearIssueIdRouteImport } from './routes/_workbench/_shell/linear/$issueId'
import { Route as WorkbenchShellProjectsProjectIdRouteRouteImport } from './routes/_workbench/_shell/projects/$projectId/route'
import { Route as WorkbenchSettingsRepoRepoIdIndexRouteImport } from './routes/_workbench/settings/repo/$repoId/index'
import { Route as WorkbenchSettingsRepoRepoIdScriptsRouteImport } from './routes/_workbench/settings/repo/$repoId/scripts'
import { Route as WorkbenchSettingsRepoRepoIdMiscRouteImport } from './routes/_workbench/settings/repo/$repoId/misc'
import { Route as WorkbenchSettingsRepoRepoIdGitRouteImport } from './routes/_workbench/settings/repo/$repoId/git'
import { Route as WorkbenchSettingsRepoRepoIdEnvironmentRouteImport } from './routes/_workbench/settings/repo/$repoId/environment'
import { Route as WorkbenchSettingsRepoRepoIdActionsRouteImport } from './routes/_workbench/settings/repo/$repoId/actions'
import { Route as WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteImport } from './routes/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/route'
import { Route as WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRouteImport } from './routes/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/index'
import { Route as WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRouteImport } from './routes/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/_workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugPiReplayRoute = DebugPiReplayRouteImport.update({
  id: '/debug/pi-replay',
  path: '/debug/pi-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchSettingsRoute = WorkbenchSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchShellRoute = WorkbenchShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchSettingsIndexRoute = WorkbenchSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkbenchSettingsRoute,
} as any)
const WorkbenchShellIndexRoute = WorkbenchShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkbenchShellRoute,
} as any)
const WorkbenchSettingsProvidersRoute =
  WorkbenchSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchSettingsModelsRoute = WorkbenchSettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => WorkbenchSettingsRoute,
} as any)
const WorkbenchSettingsIntegrationsRoute =
  WorkbenchSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchSettingsGitRoute = WorkbenchSettingsGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => WorkbenchSettingsRoute,
} as any)
const WorkbenchSettingsGeneralRoute =
  WorkbenchSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchSettingsExperimentalRoute =
  WorkbenchSettingsExperimentalRouteImport.update({
    id: '/experimental',
    path: '/experimental',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchSettingsEnvironmentRoute =
  WorkbenchSettingsEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchSettingsDiagnosticsRoute =
  WorkbenchSettingsDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchSettingsAppearanceRoute =
  WorkbenchSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchSettingsAdvancedRoute =
  WorkbenchSettingsAdvancedRouteImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchShellHistoryRoute = WorkbenchShellHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WorkbenchShellRoute,
} as any)
const WorkbenchShellHelpRoute = WorkbenchShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => WorkbenchShellRoute,
} as any)
const WorkbenchShellDashboardRoute = WorkbenchShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkbenchShellRoute,
} as any)
const WorkbenchSettingsRepoIndexRoute =
  WorkbenchSettingsRepoIndexRouteImport.update({
    id: '/repo/',
    path: '/repo/',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchShellLinearIndexRoute =
  WorkbenchShellLinearIndexRouteImport.update({
    id: '/linear/',
    path: '/linear/',
    getParentRoute: () => WorkbenchShellRoute,
  } as any)
const WorkbenchSettingsRepoRepoIdRoute =
  WorkbenchSettingsRepoRepoIdRouteImport.update({
    id: '/repo/$repoId',
    path: '/repo/$repoId',
    getParentRoute: () => WorkbenchSettingsRoute,
  } as any)
const WorkbenchShellLinearIssueIdRoute =
  WorkbenchShellLinearIssueIdRouteImport.update({
    id: '/linear/$issueId',
    path: '/linear/$issueId',
    getParentRoute: () => WorkbenchShellRoute,
  } as any)
const WorkbenchShellProjectsProjectIdRouteRoute =
  WorkbenchShellProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkbenchShellRoute,
  } as any)
const WorkbenchSettingsRepoRepoIdIndexRoute =
  WorkbenchSettingsRepoRepoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkbenchSettingsRepoRepoIdRoute,
  } as any)
const WorkbenchSettingsRepoRepoIdScriptsRoute =
  WorkbenchSettingsRepoRepoIdScriptsRouteImport.update({
    id: '/scripts',
    path: '/scripts',
    getParentRoute: () => WorkbenchSettingsRepoRepoIdRoute,
  } as any)
const WorkbenchSettingsRepoRepoIdMiscRoute =
  WorkbenchSettingsRepoRepoIdMiscRouteImport.update({
    id: '/misc',
    path: '/misc',
    getParentRoute: () => WorkbenchSettingsRepoRepoIdRoute,
  } as any)
const WorkbenchSettingsRepoRepoIdGitRoute =
  WorkbenchSettingsRepoRepoIdGitRouteImport.update({
    id: '/git',
    path: '/git',
    getParentRoute: () => WorkbenchSettingsRepoRepoIdRoute,
  } as any)
const WorkbenchSettingsRepoRepoIdEnvironmentRoute =
  WorkbenchSettingsRepoRepoIdEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => WorkbenchSettingsRepoRepoIdRoute,
  } as any)
const WorkbenchSettingsRepoRepoIdActionsRoute =
  WorkbenchSettingsRepoRepoIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => WorkbenchSettingsRepoRepoIdRoute,
  } as any)
const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute =
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => WorkbenchShellProjectsProjectIdRouteRoute,
  } as any)
const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute =
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute =
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRouteImport.update(
    {
      id: '/chats/$chatId',
      path: '/chats/$chatId',
      getParentRoute: () =>
        WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof WorkbenchShellIndexRoute
  '/settings': typeof WorkbenchSettingsRouteWithChildren
  '/debug/pi-replay': typeof DebugPiReplayRoute
  '/dashboard': typeof WorkbenchShellDashboardRoute
  '/help': typeof WorkbenchShellHelpRoute
  '/history': typeof WorkbenchShellHistoryRoute
  '/settings/advanced': typeof WorkbenchSettingsAdvancedRoute
  '/settings/appearance': typeof WorkbenchSettingsAppearanceRoute
  '/settings/diagnostics': typeof WorkbenchSettingsDiagnosticsRoute
  '/settings/environment': typeof WorkbenchSettingsEnvironmentRoute
  '/settings/experimental': typeof WorkbenchSettingsExperimentalRoute
  '/settings/general': typeof WorkbenchSettingsGeneralRoute
  '/settings/git': typeof WorkbenchSettingsGitRoute
  '/settings/integrations': typeof WorkbenchSettingsIntegrationsRoute
  '/settings/models': typeof WorkbenchSettingsModelsRoute
  '/settings/providers': typeof WorkbenchSettingsProvidersRoute
  '/settings/': typeof WorkbenchSettingsIndexRoute
  '/projects/$projectId': typeof WorkbenchShellProjectsProjectIdRouteRouteWithChildren
  '/linear/$issueId': typeof WorkbenchShellLinearIssueIdRoute
  '/settings/repo/$repoId': typeof WorkbenchSettingsRepoRepoIdRouteWithChildren
  '/linear/': typeof WorkbenchShellLinearIndexRoute
  '/settings/repo/': typeof WorkbenchSettingsRepoIndexRoute
  '/settings/repo/$repoId/actions': typeof WorkbenchSettingsRepoRepoIdActionsRoute
  '/settings/repo/$repoId/environment': typeof WorkbenchSettingsRepoRepoIdEnvironmentRoute
  '/settings/repo/$repoId/git': typeof WorkbenchSettingsRepoRepoIdGitRoute
  '/settings/repo/$repoId/misc': typeof WorkbenchSettingsRepoRepoIdMiscRoute
  '/settings/repo/$repoId/scripts': typeof WorkbenchSettingsRepoRepoIdScriptsRoute
  '/settings/repo/$repoId/': typeof WorkbenchSettingsRepoRepoIdIndexRoute
  '/projects/$projectId/workspaces/$workspaceId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/projects/$projectId/workspaces/$workspaceId/': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute
  '/projects/$projectId/workspaces/$workspaceId/chats/$chatId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkbenchShellIndexRoute
  '/debug/pi-replay': typeof DebugPiReplayRoute
  '/dashboard': typeof WorkbenchShellDashboardRoute
  '/help': typeof WorkbenchShellHelpRoute
  '/history': typeof WorkbenchShellHistoryRoute
  '/settings/advanced': typeof WorkbenchSettingsAdvancedRoute
  '/settings/appearance': typeof WorkbenchSettingsAppearanceRoute
  '/settings/diagnostics': typeof WorkbenchSettingsDiagnosticsRoute
  '/settings/environment': typeof WorkbenchSettingsEnvironmentRoute
  '/settings/experimental': typeof WorkbenchSettingsExperimentalRoute
  '/settings/general': typeof WorkbenchSettingsGeneralRoute
  '/settings/git': typeof WorkbenchSettingsGitRoute
  '/settings/integrations': typeof WorkbenchSettingsIntegrationsRoute
  '/settings/models': typeof WorkbenchSettingsModelsRoute
  '/settings/providers': typeof WorkbenchSettingsProvidersRoute
  '/settings': typeof WorkbenchSettingsIndexRoute
  '/projects/$projectId': typeof WorkbenchShellProjectsProjectIdRouteRouteWithChildren
  '/linear/$issueId': typeof WorkbenchShellLinearIssueIdRoute
  '/linear': typeof WorkbenchShellLinearIndexRoute
  '/settings/repo': typeof WorkbenchSettingsRepoIndexRoute
  '/settings/repo/$repoId/actions': typeof WorkbenchSettingsRepoRepoIdActionsRoute
  '/settings/repo/$repoId/environment': typeof WorkbenchSettingsRepoRepoIdEnvironmentRoute
  '/settings/repo/$repoId/git': typeof WorkbenchSettingsRepoRepoIdGitRoute
  '/settings/repo/$repoId/misc': typeof WorkbenchSettingsRepoRepoIdMiscRoute
  '/settings/repo/$repoId/scripts': typeof WorkbenchSettingsRepoRepoIdScriptsRoute
  '/settings/repo/$repoId': typeof WorkbenchSettingsRepoRepoIdIndexRoute
  '/projects/$projectId/workspaces/$workspaceId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute
  '/projects/$projectId/workspaces/$workspaceId/chats/$chatId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workbench': typeof WorkbenchRouteWithChildren
  '/_workbench/_shell': typeof WorkbenchShellRouteWithChildren
  '/_workbench/settings': typeof WorkbenchSettingsRouteWithChildren
  '/debug/pi-replay': typeof DebugPiReplayRoute
  '/_workbench/_shell/dashboard': typeof WorkbenchShellDashboardRoute
  '/_workbench/_shell/help': typeof WorkbenchShellHelpRoute
  '/_workbench/_shell/history': typeof WorkbenchShellHistoryRoute
  '/_workbench/settings/advanced': typeof WorkbenchSettingsAdvancedRoute
  '/_workbench/settings/appearance': typeof WorkbenchSettingsAppearanceRoute
  '/_workbench/settings/diagnostics': typeof WorkbenchSettingsDiagnosticsRoute
  '/_workbench/settings/environment': typeof WorkbenchSettingsEnvironmentRoute
  '/_workbench/settings/experimental': typeof WorkbenchSettingsExperimentalRoute
  '/_workbench/settings/general': typeof WorkbenchSettingsGeneralRoute
  '/_workbench/settings/git': typeof WorkbenchSettingsGitRoute
  '/_workbench/settings/integrations': typeof WorkbenchSettingsIntegrationsRoute
  '/_workbench/settings/models': typeof WorkbenchSettingsModelsRoute
  '/_workbench/settings/providers': typeof WorkbenchSettingsProvidersRoute
  '/_workbench/_shell/': typeof WorkbenchShellIndexRoute
  '/_workbench/settings/': typeof WorkbenchSettingsIndexRoute
  '/_workbench/_shell/projects/$projectId': typeof WorkbenchShellProjectsProjectIdRouteRouteWithChildren
  '/_workbench/_shell/linear/$issueId': typeof WorkbenchShellLinearIssueIdRoute
  '/_workbench/settings/repo/$repoId': typeof WorkbenchSettingsRepoRepoIdRouteWithChildren
  '/_workbench/_shell/linear/': typeof WorkbenchShellLinearIndexRoute
  '/_workbench/settings/repo/': typeof WorkbenchSettingsRepoIndexRoute
  '/_workbench/settings/repo/$repoId/actions': typeof WorkbenchSettingsRepoRepoIdActionsRoute
  '/_workbench/settings/repo/$repoId/environment': typeof WorkbenchSettingsRepoRepoIdEnvironmentRoute
  '/_workbench/settings/repo/$repoId/git': typeof WorkbenchSettingsRepoRepoIdGitRoute
  '/_workbench/settings/repo/$repoId/misc': typeof WorkbenchSettingsRepoRepoIdMiscRoute
  '/_workbench/settings/repo/$repoId/scripts': typeof WorkbenchSettingsRepoRepoIdScriptsRoute
  '/_workbench/settings/repo/$repoId/': typeof WorkbenchSettingsRepoRepoIdIndexRoute
  '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute
  '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId': typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/debug/pi-replay'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/diagnostics'
    | '/settings/environment'
    | '/settings/experimental'
    | '/settings/general'
    | '/settings/git'
    | '/settings/integrations'
    | '/settings/models'
    | '/settings/providers'
    | '/settings/'
    | '/projects/$projectId'
    | '/linear/$issueId'
    | '/settings/repo/$repoId'
    | '/linear/'
    | '/settings/repo/'
    | '/settings/repo/$repoId/actions'
    | '/settings/repo/$repoId/environment'
    | '/settings/repo/$repoId/git'
    | '/settings/repo/$repoId/misc'
    | '/settings/repo/$repoId/scripts'
    | '/settings/repo/$repoId/'
    | '/projects/$projectId/workspaces/$workspaceId'
    | '/projects/$projectId/workspaces/$workspaceId/'
    | '/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug/pi-replay'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/diagnostics'
    | '/settings/environment'
    | '/settings/experimental'
    | '/settings/general'
    | '/settings/git'
    | '/settings/integrations'
    | '/settings/models'
    | '/settings/providers'
    | '/settings'
    | '/projects/$projectId'
    | '/linear/$issueId'
    | '/linear'
    | '/settings/repo'
    | '/settings/repo/$repoId/actions'
    | '/settings/repo/$repoId/environment'
    | '/settings/repo/$repoId/git'
    | '/settings/repo/$repoId/misc'
    | '/settings/repo/$repoId/scripts'
    | '/settings/repo/$repoId'
    | '/projects/$projectId/workspaces/$workspaceId'
    | '/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
  id:
    | '__root__'
    | '/_workbench'
    | '/_workbench/_shell'
    | '/_workbench/settings'
    | '/debug/pi-replay'
    | '/_workbench/_shell/dashboard'
    | '/_workbench/_shell/help'
    | '/_workbench/_shell/history'
    | '/_workbench/settings/advanced'
    | '/_workbench/settings/appearance'
    | '/_workbench/settings/diagnostics'
    | '/_workbench/settings/environment'
    | '/_workbench/settings/experimental'
    | '/_workbench/settings/general'
    | '/_workbench/settings/git'
    | '/_workbench/settings/integrations'
    | '/_workbench/settings/models'
    | '/_workbench/settings/providers'
    | '/_workbench/_shell/'
    | '/_workbench/settings/'
    | '/_workbench/_shell/projects/$projectId'
    | '/_workbench/_shell/linear/$issueId'
    | '/_workbench/settings/repo/$repoId'
    | '/_workbench/_shell/linear/'
    | '/_workbench/settings/repo/'
    | '/_workbench/settings/repo/$repoId/actions'
    | '/_workbench/settings/repo/$repoId/environment'
    | '/_workbench/settings/repo/$repoId/git'
    | '/_workbench/settings/repo/$repoId/misc'
    | '/_workbench/settings/repo/$repoId/scripts'
    | '/_workbench/settings/repo/$repoId/'
    | '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId'
    | '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/'
    | '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkbenchRoute: typeof WorkbenchRouteWithChildren
  DebugPiReplayRoute: typeof DebugPiReplayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workbench': {
      id: '/_workbench'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/pi-replay': {
      id: '/debug/pi-replay'
      path: '/debug/pi-replay'
      fullPath: '/debug/pi-replay'
      preLoaderRoute: typeof DebugPiReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workbench/settings': {
      id: '/_workbench/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkbenchSettingsRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/_shell': {
      id: '/_workbench/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchShellRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/_workbench/settings/': {
      id: '/_workbench/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkbenchSettingsIndexRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/_shell/': {
      id: '/_workbench/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkbenchShellIndexRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/settings/providers': {
      id: '/_workbench/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof WorkbenchSettingsProvidersRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/models': {
      id: '/_workbench/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof WorkbenchSettingsModelsRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/integrations': {
      id: '/_workbench/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof WorkbenchSettingsIntegrationsRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/git': {
      id: '/_workbench/settings/git'
      path: '/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof WorkbenchSettingsGitRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/general': {
      id: '/_workbench/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof WorkbenchSettingsGeneralRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/experimental': {
      id: '/_workbench/settings/experimental'
      path: '/experimental'
      fullPath: '/settings/experimental'
      preLoaderRoute: typeof WorkbenchSettingsExperimentalRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/environment': {
      id: '/_workbench/settings/environment'
      path: '/environment'
      fullPath: '/settings/environment'
      preLoaderRoute: typeof WorkbenchSettingsEnvironmentRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/diagnostics': {
      id: '/_workbench/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof WorkbenchSettingsDiagnosticsRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/appearance': {
      id: '/_workbench/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof WorkbenchSettingsAppearanceRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/settings/advanced': {
      id: '/_workbench/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof WorkbenchSettingsAdvancedRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/_shell/history': {
      id: '/_workbench/_shell/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof WorkbenchShellHistoryRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/_shell/help': {
      id: '/_workbench/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof WorkbenchShellHelpRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/_shell/dashboard': {
      id: '/_workbench/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkbenchShellDashboardRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/settings/repo/': {
      id: '/_workbench/settings/repo/'
      path: '/repo'
      fullPath: '/settings/repo/'
      preLoaderRoute: typeof WorkbenchSettingsRepoIndexRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/_shell/linear/': {
      id: '/_workbench/_shell/linear/'
      path: '/linear'
      fullPath: '/linear/'
      preLoaderRoute: typeof WorkbenchShellLinearIndexRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/settings/repo/$repoId': {
      id: '/_workbench/settings/repo/$repoId'
      path: '/repo/$repoId'
      fullPath: '/settings/repo/$repoId'
      preLoaderRoute: typeof WorkbenchSettingsRepoRepoIdRouteImport
      parentRoute: typeof WorkbenchSettingsRoute
    }
    '/_workbench/_shell/linear/$issueId': {
      id: '/_workbench/_shell/linear/$issueId'
      path: '/linear/$issueId'
      fullPath: '/linear/$issueId'
      preLoaderRoute: typeof WorkbenchShellLinearIssueIdRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/_shell/projects/$projectId': {
      id: '/_workbench/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof WorkbenchShellProjectsProjectIdRouteRouteImport
      parentRoute: typeof WorkbenchShellRoute
    }
    '/_workbench/settings/repo/$repoId/': {
      id: '/_workbench/settings/repo/$repoId/'
      path: '/'
      fullPath: '/settings/repo/$repoId/'
      preLoaderRoute: typeof WorkbenchSettingsRepoRepoIdIndexRouteImport
      parentRoute: typeof WorkbenchSettingsRepoRepoIdRoute
    }
    '/_workbench/settings/repo/$repoId/scripts': {
      id: '/_workbench/settings/repo/$repoId/scripts'
      path: '/scripts'
      fullPath: '/settings/repo/$repoId/scripts'
      preLoaderRoute: typeof WorkbenchSettingsRepoRepoIdScriptsRouteImport
      parentRoute: typeof WorkbenchSettingsRepoRepoIdRoute
    }
    '/_workbench/settings/repo/$repoId/misc': {
      id: '/_workbench/settings/repo/$repoId/misc'
      path: '/misc'
      fullPath: '/settings/repo/$repoId/misc'
      preLoaderRoute: typeof WorkbenchSettingsRepoRepoIdMiscRouteImport
      parentRoute: typeof WorkbenchSettingsRepoRepoIdRoute
    }
    '/_workbench/settings/repo/$repoId/git': {
      id: '/_workbench/settings/repo/$repoId/git'
      path: '/git'
      fullPath: '/settings/repo/$repoId/git'
      preLoaderRoute: typeof WorkbenchSettingsRepoRepoIdGitRouteImport
      parentRoute: typeof WorkbenchSettingsRepoRepoIdRoute
    }
    '/_workbench/settings/repo/$repoId/environment': {
      id: '/_workbench/settings/repo/$repoId/environment'
      path: '/environment'
      fullPath: '/settings/repo/$repoId/environment'
      preLoaderRoute: typeof WorkbenchSettingsRepoRepoIdEnvironmentRouteImport
      parentRoute: typeof WorkbenchSettingsRepoRepoIdRoute
    }
    '/_workbench/settings/repo/$repoId/actions': {
      id: '/_workbench/settings/repo/$repoId/actions'
      path: '/actions'
      fullPath: '/settings/repo/$repoId/actions'
      preLoaderRoute: typeof WorkbenchSettingsRepoRepoIdActionsRouteImport
      parentRoute: typeof WorkbenchSettingsRepoRepoIdRoute
    }
    '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId': {
      id: '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof WorkbenchShellProjectsProjectIdRouteRoute
    }
    '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/': {
      id: '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/projects/$projectId/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute
    }
    '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId': {
      id: '/_workbench/_shell/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/projects/$projectId/workspaces/$workspaceId/chats/$chatId'
      preLoaderRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRouteImport
      parentRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute
    }
  }
}

interface WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteChildren {
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute
}

const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteChildren: WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteChildren =
  {
    WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute:
      WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdIndexRoute,
    WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute:
      WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdChatsChatIdRoute,
  }

const WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren =
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface WorkbenchShellProjectsProjectIdRouteRouteChildren {
  WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute: typeof WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren
}

const WorkbenchShellProjectsProjectIdRouteRouteChildren: WorkbenchShellProjectsProjectIdRouteRouteChildren =
  {
    WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRoute:
      WorkbenchShellProjectsProjectIdWorkspacesWorkspaceIdRouteRouteWithChildren,
  }

const WorkbenchShellProjectsProjectIdRouteRouteWithChildren =
  WorkbenchShellProjectsProjectIdRouteRoute._addFileChildren(
    WorkbenchShellProjectsProjectIdRouteRouteChildren,
  )

interface WorkbenchShellRouteChildren {
  WorkbenchShellDashboardRoute: typeof WorkbenchShellDashboardRoute
  WorkbenchShellHelpRoute: typeof WorkbenchShellHelpRoute
  WorkbenchShellHistoryRoute: typeof WorkbenchShellHistoryRoute
  WorkbenchShellIndexRoute: typeof WorkbenchShellIndexRoute
  WorkbenchShellProjectsProjectIdRouteRoute: typeof WorkbenchShellProjectsProjectIdRouteRouteWithChildren
  WorkbenchShellLinearIssueIdRoute: typeof WorkbenchShellLinearIssueIdRoute
  WorkbenchShellLinearIndexRoute: typeof WorkbenchShellLinearIndexRoute
}

const WorkbenchShellRouteChildren: WorkbenchShellRouteChildren = {
  WorkbenchShellDashboardRoute: WorkbenchShellDashboardRoute,
  WorkbenchShellHelpRoute: WorkbenchShellHelpRoute,
  WorkbenchShellHistoryRoute: WorkbenchShellHistoryRoute,
  WorkbenchShellIndexRoute: WorkbenchShellIndexRoute,
  WorkbenchShellProjectsProjectIdRouteRoute:
    WorkbenchShellProjectsProjectIdRouteRouteWithChildren,
  WorkbenchShellLinearIssueIdRoute: WorkbenchShellLinearIssueIdRoute,
  WorkbenchShellLinearIndexRoute: WorkbenchShellLinearIndexRoute,
}

const WorkbenchShellRouteWithChildren = WorkbenchShellRoute._addFileChildren(
  WorkbenchShellRouteChildren,
)

interface WorkbenchSettingsRepoRepoIdRouteChildren {
  WorkbenchSettingsRepoRepoIdActionsRoute: typeof WorkbenchSettingsRepoRepoIdActionsRoute
  WorkbenchSettingsRepoRepoIdEnvironmentRoute: typeof WorkbenchSettingsRepoRepoIdEnvironmentRoute
  WorkbenchSettingsRepoRepoIdGitRoute: typeof WorkbenchSettingsRepoRepoIdGitRoute
  WorkbenchSettingsRepoRepoIdMiscRoute: typeof WorkbenchSettingsRepoRepoIdMiscRoute
  WorkbenchSettingsRepoRepoIdScriptsRoute: typeof WorkbenchSettingsRepoRepoIdScriptsRoute
  WorkbenchSettingsRepoRepoIdIndexRoute: typeof WorkbenchSettingsRepoRepoIdIndexRoute
}

const WorkbenchSettingsRepoRepoIdRouteChildren: WorkbenchSettingsRepoRepoIdRouteChildren =
  {
    WorkbenchSettingsRepoRepoIdActionsRoute:
      WorkbenchSettingsRepoRepoIdActionsRoute,
    WorkbenchSettingsRepoRepoIdEnvironmentRoute:
      WorkbenchSettingsRepoRepoIdEnvironmentRoute,
    WorkbenchSettingsRepoRepoIdGitRoute: WorkbenchSettingsRepoRepoIdGitRoute,
    WorkbenchSettingsRepoRepoIdMiscRoute: WorkbenchSettingsRepoRepoIdMiscRoute,
    WorkbenchSettingsRepoRepoIdScriptsRoute:
      WorkbenchSettingsRepoRepoIdScriptsRoute,
    WorkbenchSettingsRepoRepoIdIndexRoute:
      WorkbenchSettingsRepoRepoIdIndexRoute,
  }

const WorkbenchSettingsRepoRepoIdRouteWithChildren =
  WorkbenchSettingsRepoRepoIdRoute._addFileChildren(
    WorkbenchSettingsRepoRepoIdRouteChildren,
  )

interface WorkbenchSettingsRouteChildren {
  WorkbenchSettingsAdvancedRoute: typeof WorkbenchSettingsAdvancedRoute
  WorkbenchSettingsAppearanceRoute: typeof WorkbenchSettingsAppearanceRoute
  WorkbenchSettingsDiagnosticsRoute: typeof WorkbenchSettingsDiagnosticsRoute
  WorkbenchSettingsEnvironmentRoute: typeof WorkbenchSettingsEnvironmentRoute
  WorkbenchSettingsExperimentalRoute: typeof WorkbenchSettingsExperimentalRoute
  WorkbenchSettingsGeneralRoute: typeof WorkbenchSettingsGeneralRoute
  WorkbenchSettingsGitRoute: typeof WorkbenchSettingsGitRoute
  WorkbenchSettingsIntegrationsRoute: typeof WorkbenchSettingsIntegrationsRoute
  WorkbenchSettingsModelsRoute: typeof WorkbenchSettingsModelsRoute
  WorkbenchSettingsProvidersRoute: typeof WorkbenchSettingsProvidersRoute
  WorkbenchSettingsIndexRoute: typeof WorkbenchSettingsIndexRoute
  WorkbenchSettingsRepoRepoIdRoute: typeof WorkbenchSettingsRepoRepoIdRouteWithChildren
  WorkbenchSettingsRepoIndexRoute: typeof WorkbenchSettingsRepoIndexRoute
}

const WorkbenchSettingsRouteChildren: WorkbenchSettingsRouteChildren = {
  WorkbenchSettingsAdvancedRoute: WorkbenchSettingsAdvancedRoute,
  WorkbenchSettingsAppearanceRoute: WorkbenchSettingsAppearanceRoute,
  WorkbenchSettingsDiagnosticsRoute: WorkbenchSettingsDiagnosticsRoute,
  WorkbenchSettingsEnvironmentRoute: WorkbenchSettingsEnvironmentRoute,
  WorkbenchSettingsExperimentalRoute: WorkbenchSettingsExperimentalRoute,
  WorkbenchSettingsGeneralRoute: WorkbenchSettingsGeneralRoute,
  WorkbenchSettingsGitRoute: WorkbenchSettingsGitRoute,
  WorkbenchSettingsIntegrationsRoute: WorkbenchSettingsIntegrationsRoute,
  WorkbenchSettingsModelsRoute: WorkbenchSettingsModelsRoute,
  WorkbenchSettingsProvidersRoute: WorkbenchSettingsProvidersRoute,
  WorkbenchSettingsIndexRoute: WorkbenchSettingsIndexRoute,
  WorkbenchSettingsRepoRepoIdRoute:
    WorkbenchSettingsRepoRepoIdRouteWithChildren,
  WorkbenchSettingsRepoIndexRoute: WorkbenchSettingsRepoIndexRoute,
}

const WorkbenchSettingsRouteWithChildren =
  WorkbenchSettingsRoute._addFileChildren(WorkbenchSettingsRouteChildren)

interface WorkbenchRouteChildren {
  WorkbenchShellRoute: typeof WorkbenchShellRouteWithChildren
  WorkbenchSettingsRoute: typeof WorkbenchSettingsRouteWithChildren
}

const WorkbenchRouteChildren: WorkbenchRouteChildren = {
  WorkbenchShellRoute: WorkbenchShellRouteWithChildren,
  WorkbenchSettingsRoute: WorkbenchSettingsRouteWithChildren,
}

const WorkbenchRouteWithChildren = WorkbenchRoute._addFileChildren(
  WorkbenchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkbenchRoute: WorkbenchRouteWithChildren,
  DebugPiReplayRoute: DebugPiReplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
