import type { AppLanguage } from '../../shared/i18n';

/**
 * Native menu labels in every shipped language.
 *
 * The main process gets a const table rather than an i18next instance: booting
 * the library here would pull the dependency into the main bundle and keep a
 * second copy of the catalogues, for a set of static strings that never
 * interpolate anything but the application name.
 *
 * `{{app}}` is substituted with the application name by {@link menuLabels}.
 *
 * Two macOS-owned submenus are deliberately absent — the `services` menu and
 * `startSpeaking`/`stopSpeaking` cannot be relabelled without forfeiting the
 * system integration, so they stay in the OS language. Labels for dynamic
 * submenu entries (run scripts, open-in targets, recent repositories, open
 * chats) are not here either: the renderer sends those already localized.
 */
const MENU_LABELS = {
	en: {
		about: 'About {{app}}',
		addFromGithub: 'From GitHub…',
		addFromLocal: 'From Local Folder…',
		addRepository: 'Add Repository',
		agentHarness: 'Agent Harness…',
		appearance: 'Appearance',
		archiveWorkspace: 'Archive',
		bringAllToFront: 'Bring All to Front',
		changes: 'Changes',
		chat: 'Chat',
		checkForUpdates: 'Check for Updates…',
		chooseModel: 'Choose Model…',
		closeTab: 'Close Tab',
		collapseToolCalls: 'Collapse Tool Calls',
		commandPalette: 'Command Palette…',
		commitAndPush: 'Commit and Push',
		concierge: 'Concierge',
		conciergeClear: 'Clear Context…',
		conciergeFocusComposer: 'Focus Composer',
		conciergeMaximize: 'Maximize',
		conciergeShow: 'Show Concierge',
		copy: 'Copy',
		createPullRequest: 'Create PR…',
		cut: 'Cut',
		cycleThinking: 'Cycle Thinking Level',
		delete: 'Delete',
		deleteWorkspace: 'Delete…',
		developer: 'Developer',
		diagnostics: 'Diagnostics…',
		discardChanges: 'Discard All Changes…',
		dock: 'Dock',
		edit: 'Edit',
		file: 'File',
		findFile: 'Find File…',
		fixCheckErrors: 'Fix Check Errors',
		focusComposer: 'Focus Composer',
		forceReload: 'Force Reload',
		goHistory: 'Chat History',
		goLinear: 'Linear Issues',
		goTo: 'Go To',
		goToChat: 'Go to Chat',
		goWorkbench: 'Workbench',
		help: 'Help',
		hide: 'Hide {{app}}',
		hideOthers: 'Hide Others',
		keepChatOpen: 'Keep Chat Open',
		keyboardShortcuts: 'Keyboard Shortcuts',
		mergePullRequest: 'Merge PR…',
		minimize: 'Minimize',
		newChat: 'New Chat',
		newTerminal: 'New Terminal',
		newWorkspace: 'New Workspace',
		nextChat: 'Show Next Chat',
		noOpenChats: 'No Open Chats',
		noOpenTargets: 'No Targets Installed',
		noRecentProjects: 'No Recent Repositories',
		noRunScripts: 'No Run Scripts',
		openConfigFile: 'Open Config File',
		openIn: 'Open In',
		openRecent: 'Open Recent',
		panel: 'Panel',
		panelChanges: 'Changes',
		panelChecks: 'Checks',
		panelFiles: 'All Files',
		paste: 'Paste',
		pasteAndMatchStyle: 'Paste and Match Style',
		planMode: 'Plan Mode',
		previousChat: 'Show Previous Chat',
		pushBranch: 'Push Branch',
		quickStart: 'Quick Start…',
		quit: 'Quit {{app}}',
		redo: 'Redo',
		reload: 'Reload',
		renameWorkspace: 'Rename…',
		resetZoom: 'Actual Size',
		resolveConflicts: 'Resolve Conflicts',
		review: 'Review',
		rightSidebar: 'Right Sidebar',
		run: 'Run',
		runScript: 'Run Script',
		runSetupScript: 'Run Setup Script',
		selectAll: 'Select All',
		sendMessage: 'Send Message',
		settings: 'Settings…',
		sidebar: 'Sidebar',
		speech: 'Speech',
		status: 'Status',
		statusBacklog: 'Backlog',
		statusCancelled: 'Cancelled',
		statusDone: 'Done',
		statusInProgress: 'In Progress',
		statusInReview: 'In Review',
		themeDark: 'Dark',
		themeLight: 'Light',
		themeSystem: 'System',
		toggleDevTools: 'Toggle Developer Tools',
		uncommittedChanges: 'Uncommitted Changes',
		undo: 'Undo',
		unhide: 'Show All',
		view: 'View',
		window: 'Window',
		workspace: 'Workspace',
		zoom: 'Zoom',
		zoomIn: 'Zoom In',
		zoomOut: 'Zoom Out',
	},
	ru: {
		about: 'О программе {{app}}',
		addFromGithub: 'Из GitHub…',
		addFromLocal: 'Из локальной папки…',
		addRepository: 'Добавить репозиторий',
		agentHarness: 'Харнесс…',
		appearance: 'Оформление',
		archiveWorkspace: 'Архивировать',
		bringAllToFront: 'Все окна вперёд',
		changes: 'Изменения',
		chat: 'Чат',
		checkForUpdates: 'Проверить обновления…',
		chooseModel: 'Выбрать модель…',
		closeTab: 'Закрыть вкладку',
		collapseToolCalls: 'Свернуть вызовы инструментов',
		commandPalette: 'Палитра команд…',
		commitAndPush: 'Commit и push',
		concierge: 'Консьерж',
		conciergeClear: 'Очистить контекст…',
		conciergeFocusComposer: 'Перейти к вводу',
		conciergeMaximize: 'Развернуть',
		conciergeShow: 'Показать Консьержа',
		copy: 'Скопировать',
		createPullRequest: 'Создать PR…',
		cut: 'Вырезать',
		cycleThinking: 'Уровень размышления',
		delete: 'Удалить',
		deleteWorkspace: 'Удалить…',
		developer: 'Разработчику',
		diagnostics: 'Диагностика…',
		discardChanges: 'Отменить все изменения…',
		dock: 'Док',
		edit: 'Правка',
		file: 'Файл',
		findFile: 'Найти файл…',
		fixCheckErrors: 'Исправить ошибки проверок',
		focusComposer: 'Перейти к вводу',
		forceReload: 'Принудительно перезагрузить',
		goHistory: 'История чатов',
		goLinear: 'Задачи Linear',
		goTo: 'Перейти',
		goToChat: 'Перейти к чату',
		goWorkbench: 'Главная',
		help: 'Справка',
		hide: 'Скрыть {{app}}',
		hideOthers: 'Скрыть остальные',
		keepChatOpen: 'Закрепить чат',
		keyboardShortcuts: 'Горячие клавиши',
		mergePullRequest: 'Merge PR…',
		minimize: 'Свернуть',
		newChat: 'Новый чат',
		newTerminal: 'Новый терминал',
		newWorkspace: 'Новое рабочее пространство',
		nextChat: 'Следующий чат',
		noOpenChats: 'Нет открытых чатов',
		noOpenTargets: 'Нет установленных приложений',
		noRecentProjects: 'Нет недавних репозиториев',
		noRunScripts: 'Нет скриптов запуска',
		openConfigFile: 'Файл конфигурации',
		openIn: 'Открыть в',
		openRecent: 'Недавние',
		panel: 'Панель',
		panelChanges: 'Изменения',
		panelChecks: 'Проверки',
		panelFiles: 'Все файлы',
		paste: 'Вставить',
		pasteAndMatchStyle: 'Вставить и согласовать стиль',
		planMode: 'Режим плана',
		previousChat: 'Предыдущий чат',
		pushBranch: 'Push ветки',
		quickStart: 'Быстрый старт…',
		quit: 'Завершить {{app}}',
		redo: 'Повторить',
		reload: 'Перезагрузить',
		renameWorkspace: 'Переименовать…',
		resetZoom: 'Фактический размер',
		resolveConflicts: 'Разрешить конфликты',
		review: 'Ревью',
		rightSidebar: 'Правая панель',
		run: 'Запуск',
		runScript: 'Скрипт запуска',
		runSetupScript: 'Скрипт настройки',
		selectAll: 'Выбрать все',
		sendMessage: 'Отправить сообщение',
		settings: 'Настройки…',
		sidebar: 'Боковая панель',
		speech: 'Речь',
		status: 'Статус',
		statusBacklog: 'Бэклог',
		statusCancelled: 'Отменено',
		statusDone: 'Готово',
		statusInProgress: 'В работе',
		statusInReview: 'На ревью',
		themeDark: 'Тёмная',
		themeLight: 'Светлая',
		themeSystem: 'Системная',
		toggleDevTools: 'Инструменты разработчика',
		uncommittedChanges: 'Изменения без коммита',
		undo: 'Отменить',
		unhide: 'Показать все',
		view: 'Вид',
		window: 'Окно',
		workspace: 'Пространство',
		zoom: 'Изменить масштаб',
		zoomIn: 'Увеличить',
		zoomOut: 'Уменьшить',
	},
	el: {
		about: 'Σχετικά με το {{app}}',
		addFromGithub: 'Από το GitHub…',
		addFromLocal: 'Από τοπικό φάκελο…',
		addRepository: 'Προσθήκη αποθετηρίου',
		agentHarness: 'Harness…',
		appearance: 'Εμφάνιση',
		archiveWorkspace: 'Αρχειοθέτηση',
		bringAllToFront: 'Όλα σε πρώτο πλάνο',
		changes: 'Αλλαγές',
		chat: 'Συνομιλία',
		checkForUpdates: 'Έλεγχος για ενημερώσεις…',
		chooseModel: 'Επιλογή μοντέλου…',
		closeTab: 'Κλείσιμο καρτέλας',
		collapseToolCalls: 'Σύμπτυξη κλήσεων εργαλείων',
		commandPalette: 'Παλέτα εντολών…',
		commitAndPush: 'Commit και push',
		concierge: 'Concierge',
		conciergeClear: 'Εκκαθάριση περιβάλλοντος…',
		conciergeFocusComposer: 'Μετάβαση στο πεδίο εισαγωγής',
		conciergeMaximize: 'Μεγιστοποίηση',
		conciergeShow: 'Εμφάνιση του Concierge',
		copy: 'Αντιγραφή',
		createPullRequest: 'Δημιουργία PR…',
		cut: 'Αποκοπή',
		cycleThinking: 'Επίπεδο σκέψης',
		delete: 'Διαγραφή',
		deleteWorkspace: 'Διαγραφή…',
		developer: 'Προγραμματιστής',
		diagnostics: 'Διαγνωστικά…',
		discardChanges: 'Απόρριψη όλων των αλλαγών…',
		dock: 'Dock',
		edit: 'Επεξεργασία',
		file: 'Αρχείο',
		findFile: 'Εύρεση αρχείου…',
		fixCheckErrors: 'Διόρθωση σφαλμάτων ελέγχων',
		focusComposer: 'Μετάβαση στο πεδίο εισαγωγής',
		forceReload: 'Αναγκαστική επαναφόρτωση',
		goHistory: 'Ιστορικό συνομιλιών',
		goLinear: 'Ζητήματα Linear',
		goTo: 'Μετάβαση',
		goToChat: 'Μετάβαση σε συνομιλία',
		goWorkbench: 'Πάγκος εργασίας',
		help: 'Βοήθεια',
		hide: 'Απόκρυψη {{app}}',
		hideOthers: 'Απόκρυψη άλλων',
		keepChatOpen: 'Διατήρηση συνομιλίας',
		keyboardShortcuts: 'Συντομεύσεις',
		mergePullRequest: 'Merge PR…',
		minimize: 'Ελαχιστοποίηση',
		newChat: 'Νέα συνομιλία',
		newTerminal: 'Νέο τερματικό',
		newWorkspace: 'Νέος χώρος εργασίας',
		nextChat: 'Επόμενη συνομιλία',
		noOpenChats: 'Καμία ανοιχτή συνομιλία',
		noOpenTargets: 'Καμία εγκατεστημένη εφαρμογή',
		noRecentProjects: 'Κανένα πρόσφατο αποθετήριο',
		noRunScripts: 'Κανένα σενάριο εκτέλεσης',
		openConfigFile: 'Αρχείο ρυθμίσεων',
		openIn: 'Άνοιγμα σε',
		openRecent: 'Πρόσφατα',
		panel: 'Πίνακας',
		panelChanges: 'Αλλαγές',
		panelChecks: 'Έλεγχοι',
		panelFiles: 'Όλα τα αρχεία',
		paste: 'Επικόλληση',
		pasteAndMatchStyle: 'Επικόλληση με προσαρμογή στιλ',
		planMode: 'Λειτουργία σχεδίου',
		previousChat: 'Προηγούμενη συνομιλία',
		pushBranch: 'Push κλάδου',
		quickStart: 'Γρήγορη έναρξη…',
		quit: 'Τερματισμός {{app}}',
		redo: 'Επανάληψη',
		reload: 'Επαναφόρτωση',
		renameWorkspace: 'Μετονομασία…',
		resetZoom: 'Πραγματικό μέγεθος',
		resolveConflicts: 'Επίλυση συγκρούσεων',
		review: 'Αξιολόγηση',
		rightSidebar: 'Δεξιός πίνακας',
		run: 'Εκτέλεση',
		runScript: 'Σενάριο εκτέλεσης',
		runSetupScript: 'Σενάριο εγκατάστασης',
		selectAll: 'Επιλογή όλων',
		sendMessage: 'Αποστολή μηνύματος',
		settings: 'Ρυθμίσεις…',
		sidebar: 'Πλαϊνός πίνακας',
		speech: 'Ομιλία',
		status: 'Κατάσταση',
		statusBacklog: 'Εκκρεμότητες',
		statusCancelled: 'Ακυρώθηκε',
		statusDone: 'Ολοκληρώθηκε',
		statusInProgress: 'Σε εξέλιξη',
		statusInReview: 'Σε αξιολόγηση',
		themeDark: 'Σκούρο',
		themeLight: 'Ανοιχτό',
		themeSystem: 'Συστήματος',
		toggleDevTools: 'Εργαλεία προγραμματιστή',
		uncommittedChanges: 'Αλλαγές χωρίς commit',
		undo: 'Αναίρεση',
		unhide: 'Εμφάνιση όλων',
		view: 'Προβολή',
		window: 'Παράθυρο',
		workspace: 'Χώρος',
		zoom: 'Ζουμ',
		zoomIn: 'Μεγέθυνση',
		zoomOut: 'Σμίκρυνση',
	},
} as const satisfies Record<AppLanguage, Record<string, string>>;

/** Every label the native menu renders, for one language. */
export type MenuLabels = (typeof MENU_LABELS)['en'];

/**
 * Resolves the native menu labels for a language, substituting the application
 * name into the three macOS entries that carry it.
 * @param language - The language the app is rendering in
 * @param appName - Application name, as `app.name` reports it
 * @returns Ready-to-render labels for the whole menu
 */
export function menuLabels(language: AppLanguage, appName: string): MenuLabels {
	const labels = MENU_LABELS[language];
	return Object.fromEntries(
		Object.entries(labels).map(([key, value]) => [
			key,
			value.replaceAll('{{app}}', appName),
		]),
	) as MenuLabels;
}
