/**
 * The commands the queue holds by default: test runners, type checkers,
 * builds, compiles, and system rebuilds. Installs and quick tools stay out —
 * queueing `git status` behind a ten-minute build would make the machine
 * slower to use, which is the opposite of the queue's purpose.
 */
export const DEFAULT_HEAVY_COMMAND_PATTERNS: readonly string[] = [
	'run test*',
	'run build*',
	'run typecheck*',
	'run check*',
	'run lint*',
	'run make*',
	'run package*',
	'run dist*',
	'run e2e*',
	'run compile*',
	'bun test',
	'bun build',
	'vitest',
	'jest',
	'playwright test',
	'pytest',
	'tox',
	'nox',
	'rspec',
	'deno test',
	'deno compile',
	'tsc',
	'tsgo',
	'vue-tsc',
	'eslint',
	'mypy',
	'pyright',
	'cargo build',
	'cargo b',
	'cargo test',
	'cargo t',
	'cargo check',
	'cargo c',
	'cargo clippy',
	'cargo nextest',
	'cargo bench',
	'go build',
	'go test',
	'make',
	'cmake --build',
	'ctest',
	'ninja',
	'meson compile',
	'gradle',
	'gradlew',
	'mvn',
	'mvnw',
	'sbt',
	'dotnet build',
	'dotnet test',
	'xcodebuild',
	'swift build',
	'swift test',
	'zig build',
	'bazel build',
	'bazel test',
	'cabal build',
	'stack build',
	'mix compile',
	'mix test',
	'turbo',
	'nx',
	'electron-forge',
	'electron-builder',
	'vite build',
	'next build',
	'nuxt build',
	'astro build',
	'webpack',
	'docker build',
	'docker buildx build',
	'docker compose build',
	'docker-compose build',
	'podman build',
	'nix build',
	'nix flake check',
	'nix-build',
	'nixos-rebuild',
	'darwin-rebuild',
	'home-manager switch',
	'home-manager build',
	'nh os',
	'nh home',
	'nh darwin',
];
