// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
	common: {
		actions: {
			add: 'Add';
			allow: 'Allow';
			approve: 'Approve';
			archive: 'Archive';
			archiving: 'Archiving…';
			back: 'Back';
			browse: 'Browse';
			cancel: 'Cancel';
			configure: 'Configure';
			continue: 'Continue';
			copied: 'Copied';
			'copy-code': 'Copy code';
			'copy-path': 'Copy path';
			'copy-response': 'Copy response';
			create: 'Create';
			delete: 'Delete';
			'delete-ellipsis': 'Delete…';
			deleting: 'Deleting…';
			deny: 'Deny';
			discard: 'Discard';
			'discard-changes': 'Discard changes';
			edit: 'Edit';
			'keep-open': 'Keep open';
			open: 'Open';
			'open-in': 'Open in';
			picking: 'Picking…';
			pin: 'Pin';
			remove: 'Remove';
			'remove-named': 'Remove {{label}}';
			removing: 'Removing…';
			rename: 'Rename';
			renaming: 'Renaming…';
			'reset-managed-root': 'Reset to managed repos directory';
			resolve: 'Resolve';
			restoring: 'Restoring…';
			retry: 'Retry';
			'revert-to-default': 'Revert to default';
			save: 'Save';
			saving: 'Saving…';
			send: 'Send';
			stop: 'Stop';
			'try-again': 'Try again';
			unarchive: 'Unarchive';
			unpin: 'Unpin';
			view: 'View';
		};
		'agent-question': {
			dismiss: 'Dismiss question';
			'free-text-label': 'Type your own answer';
			'free-text-placeholder': 'Type something…';
			hint: {
				dismiss: 'Esc dismiss';
				move: '↑↓ move';
				select: 'Enter select';
				submit: '{{shortcut}} submit';
				toggle: 'Enter toggle';
			};
			next: 'Next question';
			previous: 'Previous question';
			'section-label': 'Agent question';
			submit: 'Submit answers';
		};
		'answer-table': {
			collapse: 'Collapse table';
			copy: 'Copy table';
			'dialog-title': 'Table';
			expand: 'Expand table';
		};
		clipboard: {
			'path-copied': 'Path copied to clipboard.';
			'workspace-path-copied': 'Workspace path copied.';
		};
		'clone-dialog': {
			'loading-repos': 'Loading repos from GitHub…';
			'location-label': 'Location';
			'matching-repos': 'Matching repos';
			private: 'Private';
			'recent-repos': 'Recent repos';
			stage: {
				cloning: 'Cloning…';
				opening: 'Opening…';
				preparing: 'Preparing…';
				submit: 'Clone repo';
			};
			title: 'Clone GitHub repo';
			'url-label': 'Repository URL';
			'url-placeholder': 'Search repos or paste URL';
		};
		conversation: {
			'scroll-to-newest': 'Scroll to newest message';
		};
		'diagnostics-log': {
			trigger: 'Diagnostics log';
			truncated: '(truncated)';
		};
		'local-import': {
			description: 'Ensemblr is cloning the tracked git files into your managed repos folder, then creating the first workspace.';
			'still-working': 'Still working — large repositories with deep history can take a minute or two. The window will switch as soon as the workspace is ready.';
			title: 'Opening local project…';
		};
		'pi-replay': {
			'event-count_one': '{{count}} event';
			'event-count_other': '{{count}} events';
			title: 'Pi fixture replay';
		};
		'quick-start': {
			creates: 'Creates folder and repo <name>{{projectName}}</name>';
			creating: 'Creating…';
			description: 'Create a local folder and initialize a new git repository.';
			'name-label': 'Project name';
			'parent-label': 'Parent folder';
			'parent-placeholder': 'Managed repos directory';
			title: 'Create project';
		};
		'root-directory': {
			applied: 'Applied';
			applying: 'Applying';
			'change-description': 'Switch Ensemblr to the selected root and reindex/adopt from that filesystem layout after confirmation.';
			'change-title': 'Change root directory';
			'continuity-note': 'Shared Conductor root continuity covers filesystem, git, and config only; chat/session/checkpoint continuity is not guaranteed across apps.';
			'current-root': 'Current root';
			'no-blocking-warnings': 'No blocking root warnings.';
			'no-current-root': 'No current root snapshot';
			'no-reconciliation-warnings': 'No reconciliation warnings.';
			'not-applied': 'Not applied';
			'preserved-body': 'Switching changes where Ensemblr looks for repos, workspaces, and archived contexts. Reindex/adopt is the default behavior. Migration is a separate action. Delete or cleanup is a separate destructive action.';
			'preserved-title': 'Old root contents are preserved.';
			reconciliation: 'Reconciliation scanned {{repositoryDirectories}} and {{workspaceDirectories}}.';
			'repository-directory-count_one': '{{count}} repository directory';
			'repository-directory-count_other': '{{count}} repository directories';
			'result-title': 'Root switch result';
			'selected-root': 'Selected root';
			switch: 'Switch root';
			'workspace-directory-count_one': '{{count}} workspace directory';
			'workspace-directory-count_other': '{{count}} workspace directories';
		};
		'session-status': {
			context: '{{percent}}% context';
			tokens_one: '{{formatted}} token';
			tokens_other: '{{formatted}} tokens';
		};
		'setup-check': {
			optional: 'Optional';
			status: {
				failure: 'Failed';
				pending: 'Pending';
				running: 'Running';
				success: 'Ready';
				warning: 'Warning';
			};
		};
		'setup-summary': {
			blocked: {
				detail_one: '{{count}} required check needs attention before core workflows open.';
				detail_other: '{{count}} required checks need attention before core workflows open.';
				title: 'Core workflows are blocked';
			};
			'blocked-count_one': '{{count}} blocked';
			'blocked-count_other': '{{count}} blocked';
			checking: {
				detail: 'Ensemblr is collecting setup diagnostics.';
				title: 'Checking setup readiness';
			};
			group: {
				claude: 'Claude Code runtime';
				core: 'Core runtime';
				github: 'Git and GitHub';
				linear: 'Linear';
				pi: 'Pi runtime';
				storage: 'Storage';
			};
			loading: 'Loading setup diagnostics';
			'local-execution-notice': 'Agents, scripts, terminals, and tools run locally with your macOS account permissions. Workspace trusted mode is the default; stricter modes can require approval or read-only access where supported.';
			'passed-count_one': '{{count}} passed';
			'passed-count_other': '{{count}} passed';
			pending: {
				detail_one: '{{count}} required check is still pending.';
				detail_other: '{{count}} required checks are still pending.';
				title: 'Setup checks are still pending';
			};
			ready: {
				detail: '{{passedChecks}} and {{remainingWarnings}}.';
				'passed-checks_one': '{{count}} check passed';
				'passed-checks_other': '{{count}} checks passed';
				'remaining-warnings_one': '{{count}} warning remains';
				'remaining-warnings_other': '{{count}} warnings remain';
				title: 'Core workflows are ready';
			};
			retry: 'Retry checks';
			retrying: 'Retrying';
			unavailable: {
				detail: 'Setup diagnostics could not be loaded from the main process.';
				title: 'Setup diagnostics unavailable';
			};
			'warning-count_one': '{{count}} warning';
			'warning-count_other': '{{count}} warnings';
		};
		'stack-trace': {
			empty: 'No stack frames';
		};
		status: {
			'coming-soon': 'Coming soon';
		};
		terminal: {
			title: 'Terminal';
		};
		thinking: {
			reasoned: 'Reasoned for {{seconds}}s';
			reasoning: 'Reasoning… {{seconds}}s';
		};
		'tool-approval': {
			'allow-session': 'Allow for this session';
			'deny-label': 'Deny tool call';
			headline: 'Claude wants to use {{tool}}.';
			'key-hints': '1 allow · 2 allow for session · 3 deny · Esc deny';
			'section-label': 'Tool approval request';
			status: 'Approval required for {{tool}}.';
		};
		'tool-output': {
			'show-all_one': 'Show all {{count}} line';
			'show-all_other': 'Show all {{count}} lines';
		};
		'tool-row': {
			running: 'Running…';
		};
		'turn-footer': {
			actions: 'Turn actions';
			'fork-tab': 'Fork to new tab';
			'fork-workspace': 'Fork to new workspace';
			'restore-checkpoint': 'Restore to before this turn…';
			stopped: 'Stopped';
			'view-diff': 'View turn diff';
		};
		'turn-summary': {
			fallback: 'Work';
			messages_one: '{{count}} message';
			messages_other: '{{count}} messages';
			'tool-calls_one': '{{count}} tool call';
			'tool-calls_other': '{{count}} tool calls';
		};
		'turn-timer': {
			working: 'Working…';
		};
		units: {
			mb: 'MB';
			px: '{{value}}px';
			seconds: '{{seconds}}s';
			'workspace-count_one': '{{count}} workspace';
			'workspace-count_other': '{{count}} workspaces';
		};
		welcome: {
			'open-github-project': 'Open GitHub project';
			'open-project': 'Open project';
			'quick-start': 'Quick start';
		};
	};
	errors: {
		'agent-action': {
			'prompt-failed': {
				title: 'Could not prepare the action prompt.';
			};
		};
		'agent-launch': {
			failed: {
				description: '{{harness}} is not available.';
				title: 'Could not launch agent';
			};
		};
		'agent-restore': {
			failed: {
				description: 'The harness could not be resumed.';
				title: 'Could not restore agent';
			};
		};
		attachment: {
			malformed: {
				message: 'Pasted file payload was malformed.';
			};
			'read-failed': {
				message: 'Pasted file could not be read.';
			};
			'save-failed': {
				message: 'Pasted file could not be saved.';
			};
		};
		'chat-tab': {
			'dropped-submits': {
				title_one: 'Cancelled a queued action for the closed chat.';
				title_other: 'Cancelled {{count}} queued actions for the closed chat.';
			};
			'open-failed': {
				title: 'Could not open tab';
			};
			'pin-failed': {
				title: 'Could not keep tab open';
			};
			'reorder-failed': {
				title: 'Could not reorder tabs';
			};
		};
		'checkpoint-restore': {
			failed: {
				title: 'Restore failed';
			};
			restored: {
				description: 'Files reverted to before “{{label}}”.';
				title: 'Workspace restored';
			};
		};
		clone: {
			cloned: {
				title: 'Cloned {{name}}.';
			};
			'open-failed': {
				title: 'Cloned {{name}}, opening failed.';
			};
		};
		composer: {
			'no-chat-tab': {
				title: 'Open a chat tab to hand this to the agent.';
			};
		};
		'continue-branch': {
			failed: {
				title: 'Could not continue past the merged pull request.';
			};
			success: {
				title: 'Continuing on {{branch}}.';
			};
		};
		'diff-comment': {
			'update-failed': {
				title: 'Comment update failed';
			};
		};
		'discard-changes': {
			failed: 'Could not discard changes.';
		};
		fork: {
			failed: {
				title: 'Fork failed.';
			};
			'new-tab': {
				title: 'Forked to a new tab.';
			};
			'new-workspace': {
				title: 'Forked to workspace {{name}}.';
			};
			'summary-failed': {
				title: 'Fork summary could not be written.';
			};
			'workspace-failed': {
				title: 'The fork workspace could not be created.';
			};
		};
		merge: {
			failed: {
				title: 'Merge failed';
			};
		};
		'open-local-project': {
			'bridge-unavailable': {
				title: 'Preload bridge is unavailable in this context.';
			};
			'import-failed': {
				title: 'The repository could not be imported.';
			};
			opened: {
				title: 'Opened {{name}}.';
			};
			'seed-failed': {
				title: "Imported {{name}} but couldn't open a workspace.";
			};
			unexpected: {
				title: 'The local project could not be opened.';
			};
		};
		'open-target': {
			'bridge-unavailable': {
				title: 'Open in… is unavailable without the Electron bridge.';
			};
			'open-failed': {
				title: 'Failed to open in {{target}}: {{error}}';
			};
			'settings-open-failed': {
				title: 'Failed to open the settings file in {{target}}.';
			};
		};
		'plan-handoff': {
			failed: {
				title: 'Plan handoff failed.';
			};
		};
		'pull-request-refresh': {
			failed: {
				title: 'Pull request refresh failed';
			};
		};
		push: {
			failed: {
				title: 'Push failed';
			};
			success: {
				title: 'Branch pushed.';
			};
		};
		'quick-start': {
			created: {
				title: 'Created project {{name}}.';
			};
			'open-failed': {
				title: 'Created {{name}}, opening failed.';
			};
		};
		'repo-settings': {
			'save-failed': {
				title: 'Could not save repository settings.';
			};
		};
		'review-action': {
			failed: {
				description: 'GitHub action failed.';
			};
		};
		'review-todo': {
			failed: {
				title: 'Todo update failed';
			};
		};
		'route-error': {
			detail: 'Route data failed to load.';
			'health-detail': 'TanStack Router caught a route-level failure.';
			'health-label': 'Route error';
			title: 'Route unavailable';
		};
		'route-not-found': {
			detail: 'The requested route does not exist.';
			'health-detail': 'Choose another route from the workspace navigation.';
			'health-label': 'Not found';
			title: 'Page not found';
		};
		'route-pending': {
			detail: 'Ensemblr is reading repositories and workspaces from SQLite.';
			'health-detail': 'Renderer route data is loading.';
			'health-label': 'Loading';
			title: 'Loading repositories';
		};
		'script-settings': {
			'save-failed': {
				title: 'Could not save script settings.';
			};
		};
		'seed-workspace': {
			'create-failed': {
				message: 'The starter workspace could not be created.';
			};
			'not-in-snapshot': {
				message: 'The starter workspace was created, but the navigation snapshot did not include it yet.';
			};
			'open-failed': {
				message: 'The starter workspace was created, but it could not be opened.';
			};
			'refresh-failed': {
				message: 'The starter workspace was created, but the navigation snapshot could not be refreshed.';
			};
		};
		'setup-script': {
			'chat-failed': {
				description: 'Try the "Ask agent" action again from the setup tab.';
				title: 'Could not open a new chat.';
			};
			'chat-ready': {
				description: 'Send the prompt to have the agent create .ensemblr/settings.toml — edit it first if needed.';
				title: 'New chat ready for setup.';
			};
		};
		'target-branch': {
			'retarget-failed': {
				title: 'Could not change the target branch.';
			};
		};
		terminal: {
			'start-failed': {
				title: 'The terminal could not start.';
			};
		};
		'workspace-archive': {
			archived: {
				title: 'Workspace archived.';
			};
			failed: {
				title: 'Archiving the workspace failed.';
			};
			skipped: {
				title: 'The workspace was not archived.';
			};
		};
		'workspace-create': {
			failed: {
				title: 'Failed to create workspace.';
			};
		};
	};
	git: {
		actions: {
			'commit-and-push': 'Commit and push';
			merge: 'Merge';
			push: 'Push';
		};
		'branch-picker': {
			'default-tag': 'default';
			'empty-remote': 'No remote branches found.';
			loading: 'Loading branches…';
			'no-match': 'No branches match.';
			'use-typed-ref': 'Use <ref>{{typedRef}}</ref>';
		};
		'changes-source': {
			all: 'All changes';
			'changed-file-count_one': '{{count}} file changed';
			'changed-file-count_other': '{{count}} files changed';
			'commits-empty': 'No commits yet.';
			'commits-failed': 'Could not load commits.';
			'commits-loading': 'Loading commits…';
			'discard-all': 'Discard all uncommitted changes';
			'menu-label': 'Open changes menu';
			uncommitted: 'Uncommitted changes';
			'uncommitted-badge': 'Uncommitted';
			'uncommitted-empty': 'No uncommitted changes';
		};
		'commit-and-push': {
			asked: {
				title: 'Asked the agent to commit and push.';
			};
		};
		'create-pull-request': {
			draft: 'Create draft PR';
			manual: 'Create PR manually';
			'options-label': 'Open create pull request options';
		};
		'git-status': {
			action: {
				'commit-push': 'Commit and push';
				push: 'Push';
				'push-branch': 'Push branch';
			};
			clean: 'Up to date with remote';
			uncommitted_one: '{{count}} uncommitted change';
			uncommitted_other: '{{count}} uncommitted changes';
			unpublished: 'Branch not pushed yet';
			unpushed_one: '{{count}} unpushed commit';
			unpushed_other: '{{count}} unpushed commits';
		};
		'merge-conflicts': {
			asked: {
				title: 'Asked the agent to resolve the merge conflicts.';
			};
		};
		'merge-dialog': {
			'after-merge-archive': 'Workspace will be archived';
			'after-merge-archive-branch': 'Workspace will be archived and the local branch deleted';
			'after-merge-label': 'After merge';
			'after-merge-stay': 'Workspace stays open (archive offered after merge)';
			'checks-blocked': '{{failing}} failing, {{pending}} pending';
			'checks-label': 'Checks';
			'checks-none': 'No checks reported';
			'checks-passed': 'All checks passed';
			'comments-clear': 'No unresolved comments';
			'comments-label': 'Comments';
			'comments-unresolved_one': '{{count}} unresolved';
			'comments-unresolved_other': '{{count}} unresolved';
			confirm: 'Confirm merge';
			'confirm-override': 'Merge anyway';
			description: 'Merges <mono>{{branch}}</mono> through <mono>{{command}}</mono>. This action is visible to everyone on the repository and cannot be undone from Ensemblr.';
			submitting: 'Merging…';
			title: 'Merge pull request';
			'title-numbered': 'Merge pull request #{{number}}';
			'todos-clear': 'No open todos';
			'todos-label': 'Todos';
			'todos-open_one': '{{count}} open';
			'todos-open_other': '{{count}} open';
			'warning-blocked': 'Required checks have not passed. Merging now overrides merge readiness and only succeeds if repository policy allows it.';
			'warning-not-ready': 'This pull request is not marked ready to merge. Continue only if you are sure.';
		};
		'preview-deployment': {
			open: 'Open preview deployment';
			'open-provider': 'Open {{provider}} preview deployment';
		};
		'pull-request': {
			'create-action': 'Create PR';
			'description-field': 'PR description';
			detail: {
				blocked: 'Resolve failing checks or review blockers before merge.';
				checking: 'Checks are still running.';
				closed: 'This pull request was closed without merging.';
				conflicting: 'Merge conflicts must be resolved.';
				draft: 'Draft pull request — mark ready for review to run policy gates.';
				merged: 'This pull request has been merged.';
				'no-pull-request': 'No pull request for this branch yet.';
				open: 'Pull request is open.';
				'ready-to-merge': 'All required checks passed.';
				'sync-failed': 'Could not refresh GitHub state: {{error}}';
			};
			label: {
				blocked: 'Blocked';
				checking: 'Checks running';
				closed: 'Closed';
				conflicts: 'Merge conflicts';
				draft: 'Draft';
				merged: 'Merged';
				'no-pull-request': 'No PR';
				'ready-to-merge': 'Ready to merge';
			};
			'open-number': 'Open pull request #{{number}}';
			'title-field': 'PR title';
			'update-action': 'Update PR';
		};
		'pull-request-create': {
			asked: {
				title: 'Asked the agent to open a pull request.';
			};
		};
		'pull-request-create-draft': {
			asked: {
				title: 'Asked the agent to open a draft pull request.';
			};
		};
		'pull-request-header': {
			activity: 'Pull request activity in progress';
			'agent-working': 'Agent working';
		};
		'pull-request-menu': {
			label: 'Open pull request menu';
			'open-on-github': 'Open on GitHub';
			refresh: 'Refresh PR status';
			'resolve-conflicts': 'Resolve conflicts';
		};
		'pull-request-update': {
			asked: {
				title: 'Asked the agent to update the pull request.';
			};
		};
	};
	linear: {
		'comment-composer': {
			label: 'Add a comment';
			placeholder: 'Add a comment…';
			posting: 'Posting…';
			submit: 'Comment';
		};
		'connection-gate': {
			'not-configured': {
				description: 'Add app.linear.clientId to ~/.config/ensemblr/config.json, then connect from integration settings.';
				title: 'Linear is not configured';
			};
			'not-connected': {
				description: 'Connect Linear from integration settings to browse issues, manage them from Ensemblr, and create workspaces from issues.';
				title: 'Linear is not connected';
			};
			'open-settings': 'Open integration settings';
			'reconnect-required': {
				title: 'Linear needs to be reconnected';
			};
		};
		'create-workspace': {
			creating: 'Creating…';
			'menu-label': 'Create in repository';
			trigger: 'Create workspace';
		};
		failure: {
			'not-connected': 'Linear is not connected. Sign in from integration settings.';
			'not-found': 'This Linear issue no longer exists or is not visible to you.';
			'permission-denied': 'Your Linear account does not have permission for this action.';
			'rate-limited': 'Linear rate limit reached. Try again shortly.';
			'rate-limited-retry': 'Linear rate limit reached. Try again in {{seconds}}s.';
			'reconnect-required': 'The Linear connection expired. Reconnect from integration settings.';
			unreachable: 'Linear is unreachable. Showing cached data where available.';
		};
		'issue-badges': {
			archived: 'Archived';
		};
		'issue-detail': {
			back: 'Back to issues';
			'load-failed': 'This Linear issue could not be loaded.';
			'no-comments': 'No comments yet.';
			'no-description': 'No description.';
			'open-external': 'Open in Linear';
			refresh: 'Refresh issue';
			'unknown-author': 'Unknown';
		};
		'issue-editor': {
			'description-create': 'Create an issue in the connected Linear workspace.';
			'description-edit': 'Update fields where your Linear permissions allow.';
			field: {
				assignee: 'Assignee';
				cycle: 'Cycle';
				description: 'Issue description';
				'description-placeholder': 'Description (markdown)';
				'due-date': 'Due date';
				priority: 'Priority';
				project: 'Project';
				status: 'Status';
				team: 'Team';
				title: 'Issue title';
			};
			priority: {
				high: 'High';
				low: 'Low';
				medium: 'Medium';
				none: 'No priority';
				urgent: 'Urgent';
			};
			saving: 'Saving…';
			'submit-create': 'Create issue';
			'submit-edit': 'Save changes';
			'title-create': 'New Linear issue';
			'title-edit': 'Edit {{identifier}}';
			'unset-option': '{{field}}: none';
		};
		'issue-list': {
			'all-teams': 'All teams';
			empty: 'No Linear issues are cached yet. Refresh to sync from Linear.';
			'empty-search': 'No issues match your search.';
			'new-issue': 'New issue';
			refresh: 'Refresh issues';
			'search-label': 'Search Linear issues';
			'search-placeholder': 'Search by identifier or title…';
		};
		'issue-picker': {
			description: 'Search Linear issues and pick one to link.';
			empty: 'No issues match your search.';
			loading: 'Loading issues…';
			'not-connected': 'Linear is not connected. Sign in from integration settings.';
			'search-placeholder': 'Search by identifier or title…';
			title: 'Link Linear issue';
		};
		'linked-issue': {
			connect: 'Connect Linear';
			reconnect: 'Reconnect Linear';
			refresh: 'Refresh linked issue';
			'refresh-status': 'Refresh linked issue status';
			'set-status': 'Set status';
			'set-status-menu': 'Update Linear status';
			status: {
				deleted: 'Deleted in Linear';
				'no-access': 'No access';
				'rate-limited': 'Rate limited';
				unavailable: 'Status unavailable';
			};
			'update-failed': 'Updating the Linear status failed.';
			updating: 'Updating…';
		};
		priority: {
			high: 'High';
			low: 'Low';
			medium: 'Medium';
			none: 'No priority';
			urgent: 'Urgent';
		};
	};
	onboarding: {
		card: {
			status: {
				failure: 'Not found';
				pending: 'Waiting';
				running: 'Checking';
				subdued: 'Not installed';
				success: 'Ready';
				warning: 'Not connected';
			};
		};
		checks: {
			'claude-executable': 'Claude Code';
			'gh-auth': 'GitHub CLI signed in';
			'gh-cli': 'GitHub CLI installed';
			'linear-oauth': 'Linear account';
			'pi-executable': 'Pi';
		};
		footer: {
			continue: 'Continue';
			defer: "I'll do this later";
			finish: 'Open Ensemblr';
			recheck: 'Check again';
			rechecking: 'Checking…';
		};
		header: {
			eyebrow: 'Ensemblr Setup';
			progress: '{{satisfied}} of {{total}} required';
		};
		rail: {
			label: 'Setup steps';
			optional: 'Optional';
		};
		ready: {
			lead: 'Ensemblr is ready to open its first workspace.';
			outstanding: '{{step}} is still unresolved';
			'partial-lead': 'You can start now, but some things will not work until these are done. Settings → Diagnostics has them whenever you are ready.';
			'partial-title': 'Almost there';
			title: "You're all set";
		};
		screens: {
			'agent-cli': {
				'blocked-cta': 'Install an agent CLI';
				empty: 'No agent runtime is compiled into this build, so there is nothing to install.';
				lead: "Ensemblr drives Pi and Claude Code as local processes on this machine. Install either one — you don't need both.";
				title: 'Install an agent CLI';
			};
			github: {
				'blocked-cta': 'Sign in to gh';
				empty: 'The GitHub CLI is not wired into this build, so there is nothing to connect.';
				lead: 'Branch, pull request, review, and merge workflows shell out to gh. It needs to be installed and signed in.';
				title: 'Connect the GitHub CLI';
			};
			linear: {
				'blocked-cta': 'Skip for now';
				empty: 'Linear is not configured for this build, so there is nothing to connect.';
				lead: 'Browse issues and open workspaces straight from them. Ensemblr works fine without it.';
				title: 'Connect Linear';
			};
		};
		steps: {
			'agent-cli': 'Agent CLI';
			github: 'GitHub';
			linear: 'Linear';
			ready: 'Ready';
			welcome: 'Welcome';
		};
		welcome: {
			lead: 'Ensemblr runs coding agents and the GitHub CLI as local processes. A short check confirms they are there — it takes about a minute.';
			requirements: {
				'agent-cli': {
					detail: 'Pi or Claude Code';
					label: 'An agent CLI';
				};
				github: {
					detail: 'Installed and signed in';
					label: 'GitHub CLI';
				};
				linear: {
					detail: 'Optional';
					label: 'Linear';
				};
			};
			skip: 'Skip setup';
			start: 'Get started';
			title: "Let's get your machine ready";
		};
	};
	review: {
		changes: {
			empty: {
				message: 'Changes appear here.';
				title: 'No file changes yet';
			};
			'group-clean': 'Clean';
			'group-conflicts': 'Conflicts';
			loading: 'Loading changes…';
		};
		'check-status': {
			failed: 'Failed';
			passed: 'Passed';
			running: 'Running';
		};
		checks: {
			'add-all-to-chat': 'Add all to chat';
			'add-todo': '+ Add';
			'check-details-link': '{{label}} check details (opens in new tab)';
			checks: 'Checks';
			comments: 'Comments';
			conflicts: 'Conflicts';
			'git-status': 'Git status';
			'no-checks': 'No checks reported';
			'no-comments': 'No comments yet';
			'no-pull-request': 'No PR open';
			'no-todos': 'No todos yet';
			'sync-error': {
				title: 'Could not refresh from GitHub';
			};
			'todo-input-label': 'New todo title';
			'todo-placeholder': 'Todo title';
			todos: 'Your todos';
			'uncommitted-change-count_one': '{{count}} uncommitted change';
			'uncommitted-change-count_other': '{{count}} uncommitted changes';
		};
		comment: {
			'add-to-chat': 'Add comment to chat';
			'added-to-chat': {
				title: 'Comment added to chat.';
			};
			'agent-badge': 'Agent';
			'composer-label': 'New line comment';
			'composer-placeholder': 'Add a local review comment on this line…';
			delete: 'Delete comment';
			'go-to-line': 'Go to line in diff';
			hide: 'Hide comment';
			outdated: 'Outdated';
			reopen: 'Reopen comment';
			resolve: 'Resolve comment';
			resolved: 'Resolved';
			'source-actions-bot': 'Actions bot';
			'source-local': 'Local';
			submit: 'Comment';
			unresolved: 'Unresolved';
		};
		'comment-preview': {
			actions: {
				'add-to-chat': 'Add comment to chat';
				'open-external': 'Open comment on {{provider}}';
			};
			'added-to-chat': {
				title: 'Comment added to chat.';
			};
			'reply-count_one': '{{count}} reply';
			'reply-count_other': '{{count}} replies';
			state: {
				outdated: 'Outdated';
				unresolved: 'Unresolved';
			};
		};
		comments: {
			'added-to-chat': {
				title: 'Outstanding comments added to chat.';
			};
		};
		'diff-toolbar': {
			'disable-word-wrap': 'Disable word wrap';
			'enable-word-wrap': 'Enable word wrap';
			'hide-whitespace': 'Hide hidden characters';
			'mark-viewed': 'Mark viewed';
			'mode-diff': 'Diff';
			'mode-file': 'File';
			'mode-file-unavailable': 'Full file view is unavailable for this diff';
			'show-whitespace': 'Show hidden characters';
			'split-view': 'Split view';
			'unified-view': 'Unified view';
			'unmark-viewed': 'Unmark viewed';
			viewed: 'Viewed';
		};
		'diff-viewer': {
			'add-comment': 'Add comment';
			'hidden-line-count_one': '{{count}} unchanged line';
			'hidden-line-count_other': '{{count}} unchanged lines';
			'unchanged-lines': 'Unchanged lines';
		};
		'discard-changes': {
			'affected-file-count_one': '{{count}} file affected';
			'affected-file-count_other': '{{count}} files affected';
			description: 'The working-tree changes are reverted to the last commit; a new file is deleted. This cannot be undone.';
			'description-bulk': 'Every working-tree change is reverted to the last commit and any new files are deleted. This cannot be undone.';
			submitting: 'Discarding…';
			title: 'Discard changes?';
			'title-bulk': 'Discard all changes?';
		};
		'file-diff': {
			'add-diff-to-chat': 'Add diff to chat';
			'add-to-chat': 'Add to chat';
			'added-to-chat': {
				title: 'Diff added to {{chat}}.';
			};
			'fallback-chat-name': 'chat';
			'latest-chat': 'latest';
			truncated: 'Diff truncated';
			'untitled-chat': 'Untitled chat';
		};
		'file-menu': {
			actions: '{{path}} actions';
		};
		'file-row': {
			discard: 'Discard changes to {{path}}';
			open: 'Open {{path}}';
			'open-in': 'Open {{path}} in…';
			viewed: 'Viewed';
		};
		'file-status': {
			added: 'Added';
			conflicted: 'Conflicted';
			deleted: 'Deleted';
			modified: 'Modified';
			renamed: 'Renamed';
			untracked: 'Untracked';
		};
		'review-panel': {
			'refresh-pull-request': 'Refresh pull request status';
			'review-action': 'Review';
			'search-files': 'Search files';
			tabs: {
				changes: 'Changes';
				checks: 'Checks';
				files: 'All files';
			};
			'view-mode': {
				'as-folders': 'Show changes as folders';
				'as-list': 'Show changes as list';
			};
		};
		todo: {
			'add-to-chat': 'Add todo to chat';
			'added-to-chat': {
				title: 'Todo added to chat.';
			};
			delete: 'Delete todo';
			'mark-done': 'Mark todo done: {{label}}';
			'mark-open': 'Mark todo open: {{label}}';
		};
	};
	settings: {
		advanced: {
			description: 'Root directory, Pi executable override, and terminal-scrollback limits.';
			'pi-executable': {
				description: 'Override the bundled Pi executable with a custom one. Leave empty to use the discovered system Pi (recommended).';
				label: 'Pi executable path';
				'use-bundled': 'Use bundled Pi';
			};
			'root-directory': {
				description: 'Where Ensemblr stores repositories and workspaces. This should be an empty directory you do not modify directly. Changing this will reconcile your repository list against the new root.';
				label: 'Ensemblr root directory';
				reading: 'Reading root…';
				source: 'source: {{source}}';
				unset: 'Not configured';
			};
			scrollback: {
				'aria-label': 'Terminal scrollback limit in megabytes';
				description: 'Maximum size of each terminal pane scrollback buffer. Larger values keep more history at the cost of memory.';
				label: 'Terminal scrollback limit';
			};
			title: 'Advanced';
		};
		appearance: {
			'accessible-colors': {
				default: 'Default';
				description: 'Theme optimized for color vision differences.';
				deuteranopia: 'Deuteranopia';
				label: 'Accessible colors';
				protanopia: 'Protanopia';
				tritanopia: 'Tritanopia';
			};
			'code-ligatures': {
				description: 'Use font ligatures in file editors and diffs.';
				label: 'Code ligatures';
			};
			'code-theme': {
				description: 'Syntax highlighting for code blocks and editors. Each theme follows the app theme, using its light cut in light mode and its dark cut in dark mode.';
				label: 'Code theme';
			};
			'markdown-style': {
				compact: 'Compact';
				default: 'Default';
				description: 'Rendering style for markdown files.';
				label: 'Markdown style';
				prose: 'Prose';
			};
			'mono-font': {
				'aria-label': 'Mono font name';
				description: 'Font used for code and diffs. The bundled Nerd Font is the default; custom fonts must be installed on your system.';
				label: 'Mono font';
			};
			'terminal-font': {
				'aria-label': 'Terminal font name';
				description: 'The bundled Nerd Font is the default; enter another font name exactly as installed to override it.';
				label: 'Terminal font';
			};
			'terminal-font-size': {
				description: 'Adjust the size of text in the integrated terminal.';
				label: 'Terminal font size';
			};
			theme: {
				dark: 'Dark';
				description: 'Toggle with ⌘⌥T.';
				label: 'Theme';
				light: 'Light';
				system: 'System';
			};
			title: 'Appearance';
		};
		diagnostics: {
			'copy-bundle': 'Copy diagnostics bundle';
			description: 'Setup gate checks for Pi, git, GitHub, Linear, and the Ensemblr runtime. The diagnostics bundle redacts secrets, account ids, and full paths before going to the clipboard.';
			title: 'Diagnostics';
		};
		environment: {
			add: 'Add environment variable';
			description: 'Environment variables used by Ensemblr and passed to agent sessions, scripts, and terminals.';
			documented: {
				'add-aria-label': 'Add {{name}}';
				hide: 'Hide documented variables';
				'not-set': 'Not set';
				show_one: 'Show documented variables ({{count}})';
				show_other: 'Show documented variables ({{count}})';
			};
			empty: {
				description: 'Add a variable to make it available in this environment.';
				title: 'No variables set';
			};
			'env-files': {
				add: 'Add env file';
				'browse-aria-label': 'Browse for env file';
				description: 'Load environment variables from env files. In the native file picker, press <kbd>Cmd+Shift+.</kbd> to show hidden files.';
				'remove-aria-label': 'Remove {{path}}';
				title: 'Env files';
			};
			loading: 'Reading environment…';
			'read-failed': 'Failed to read environment: {{error}}.';
			row: {
				delete: 'Delete variable';
				edit: 'Edit variable';
				'hide-value': 'Hide value';
				'show-value': 'Show value';
			};
			sheet: {
				'edit-title': 'Edit environment variable';
				'empty-value-hint': 'Use an empty value to set this variable to an empty string.';
				name: 'Name';
				'name-rule': 'Variable names may only contain letters, numbers, and underscores.';
				value: 'Value';
				'value-required': 'A value is required.';
			};
			title: 'Environment';
		};
		experimental: {
			'auto-run': {
				description: "Start a repository's run script automatically after setup when no repository-specific setting overrides it.";
				label: 'Auto-run after setup';
			};
			description: 'Developer-only controls and early automation defaults.';
			'developer-mode': {
				description: 'Show developer-only diagnostics and Pi debug controls.';
				label: 'Developer Mode';
			};
			title: 'Experimental';
		};
		general: {
			'auto-convert': {
				description: 'Convert pasted text over 5000 characters into text attachments.';
				label: 'Auto-convert long text';
			};
			caffeinate: {
				description: 'Prevent your Mac from sleeping while an agent is actively working. Shuts off below 10% battery.';
				label: 'Caffeinate while agents are running';
			};
			'context-usage': {
				description: 'Always show context usage. By default, only shown when more than 70% is used.';
				label: 'Always show context usage';
			};
			'follow-up': {
				block: 'Block';
				description: 'Queue messages to send after the agent finishes, or steer the agent mid-turn. Use ⌘J to queue.';
				label: 'Follow-up behavior';
				queue: 'Queue';
				steer: 'Steer';
			};
			language: {
				description: 'Interface language. System follows your macOS language order.';
				label: 'Language';
				system: 'System';
			};
			notifications: {
				description: 'Get notified when an agent finishes working in a chat.';
				label: 'Desktop notifications';
			};
			'send-shortcut': {
				description: 'Use {{shortcut}} for new lines.';
				label: 'Send messages with';
			};
			title: 'General';
			'tool-calls': {
				description: 'Show all tool calls expanded by default instead of collapsed. Toggle with {{shortcut}}.';
				label: "Don't collapse tool calls";
			};
		};
		git: {
			'archive-on-merge': {
				description: 'Automatically archive a workspace after merging its PR.';
				label: 'Archive on merge';
			};
			'branch-prefix': {
				custom: 'Custom:';
				'custom-aria-label': 'Custom branch prefix';
				description: 'Prefix for new workspace branch names.';
				'github-username': 'GitHub username (resolved via `gh`)';
				label: 'Branch name prefix';
				none: 'None';
			};
			'delete-branch': {
				description: 'Delete the local branch when archiving a workspace. To delete the remote branch, configure it on GitHub.';
				label: 'Delete branch on archive';
			};
			description: 'Workspace branch defaults and lifecycle behavior. Repository-scope overrides win when set.';
			'rename-workspace': {
				description: 'Ask the agent to rename a workspace from its placeholder composer name, and its git branch to match, once it knows what the work is. Off leaves the placeholder name in place.';
				label: 'Let agents name the workspace and branch';
			};
			'set-upstream': {
				description: 'Configure new Ensemblr workspaces so plain `git push` sets a branch upstream. Turning this off avoids writing Git worktree config, but PR info may be less reliable until branches have an upstream.';
				label: 'Set upstream on plain `git push`';
			};
			title: 'Git';
		};
		header: {
			'edit-config': 'Edit in {{file}}';
			'open-menu': {
				'aria-label': '{{label}} — choose an app';
			};
			'open-primary': {
				'aria-label': '{{label}} in {{app}}';
			};
			'repo-picker': {
				'aria-label': 'Active repository';
				placeholder: 'Select repository';
			};
			'scope-repo': 'Repo';
			'scope-user': 'User';
		};
		integrations: {
			linear: {
				'browse-issues': 'Browse issues';
				checking: 'Checking the Linear connection…';
				connect: 'Connect';
				connected: 'Connected to Linear.';
				'connected-as': 'Connected as {{identity}}.';
				'connected-as-in': 'Connected as {{identity}} in {{organization}}.';
				disconnect: 'Disconnect';
				disconnected: 'Connect Linear to browse issues, manage them from Ensemblr, and create workspaces from issues.';
				disconnecting: 'Disconnecting…';
				'not-configured': 'Add app.linear.clientId to ~/.config/ensemblr/config.json to enable Linear sign-in. Linear is optional for local and GitHub-only workflows.';
				reconnect: 'Reconnect';
				'reconnect-required': 'The stored Linear token expired and cannot be refreshed automatically. Reconnect to continue using Linear workflows.';
				'state-connected': 'Connected';
				'state-disconnected': 'Disconnected';
				'state-not-configured': 'Not configured';
				'state-reconnect': 'Reconnect required';
				waiting: 'Waiting for browser…';
			};
			title: 'Integrations';
		};
		models: {
			'default-model': {
				'aria-label': 'Default chat model';
				description: 'Model used when you start a new chat. Falls back to the agent-reported default when unset.';
				label: 'Default model';
				'thinking-aria-label': 'Default thinking level';
			};
			description: "Agent models and thinking-level defaults for new chats and reviews. Sourced from each configured runtime's capability discovery.";
			'discovery-failed': 'Model discovery failed: {{error}}.';
			loading: 'Loading models…';
			'no-models': 'No models';
			'review-model': {
				'aria-label': 'Review model';
				description: 'Model used for the Review action on a workspace.';
				label: 'Review model';
				'thinking-aria-label': 'Review thinking level';
			};
			thinking: {
				'effort-placeholder': 'Effort level';
				level: {
					high: 'High';
					low: 'Low';
					max: 'Max';
					medium: 'Medium';
					minimal: 'Minimal';
					off: 'No thinking';
					xhigh: 'Extra high';
				};
				'thinking-placeholder': 'Thinking level';
			};
			title: 'Models';
			visibility: {
				description: 'Hide models you don’t use from the model picker and the default/review selects. Hiding the selected default or review model switches it to the first available.';
				empty: 'No models available.';
				'hidden-count_one': '{{count}} of {{total}} hidden.';
				'hidden-count_other': '{{count}} of {{total}} hidden.';
				'hide-model': 'Hide {{model}}';
				'hide-provider': 'Hide all {{provider}} models';
				label: 'Model visibility';
				locked: 'At least one model must stay visible';
				'no-matches': 'No models match “{{query}}”.';
				'search-aria-label': 'Search models';
				'search-placeholder': 'Search models…';
				'show-all': 'Show all';
				'show-model': 'Show {{model}}';
				'show-provider': 'Show all {{provider}} models';
			};
		};
		nav: {
			advanced: 'Advanced';
			appearance: 'Appearance';
			'aria-label': 'Settings sections';
			diagnostics: 'Diagnostics';
			environment: 'Environment';
			experimental: 'Experimental';
			general: 'General';
			git: 'Git';
			integrations: 'Integrations';
			models: 'Models';
			more: 'More';
			providers: 'Providers';
		};
		providers: {
			account: {
				'api-provider': 'API provider';
				'credential-source': 'Credential source';
				description: 'Reported by the provider for the credentials Ensemblr will use.';
				email: 'Account';
				empty: 'The provider reported no account details.';
				label: 'Account';
				organization: 'Organization';
				plan: 'Plan';
			};
			'check-status': {
				failure: 'Failed';
				success: 'Ready';
				warning: 'Warning';
			};
			checking: 'Checking {{provider}}…';
			checks: {
				description: 'Everything Ensemblr probes before it will start a chat on this runtime.';
				label: 'Readiness checks';
			};
			'copy-command': 'Copy {{command}}';
			description: 'Agent runtimes that can drive a chat. Each one resolves its own executable, reports its own readiness, and keeps its own credentials.';
			executable: {
				description: 'Override the discovered {{command}} binary with a custom one. Leave empty to use the executable found on PATH (recommended).';
				label: '{{provider}} executable path';
				'not-found': 'Not found';
				resolved: 'Resolved executable';
				source: 'source: {{source}}';
				'use-discovered': 'Use discovered {{command}}';
			};
			'executable-source': {
				configured: 'a configured override';
				missing: 'nothing — no executable resolved';
				path: 'the executable found on PATH';
			};
			refresh: 'Refresh';
			refreshing: 'Refreshing…';
			runtime: {
				'probe-failed': 'Ensemblr could not probe the {{command}} executable.';
				probing: 'Probing the {{command}} executable…';
				resolved: '{{runtime}}, running from {{origin}}.';
				'resolved-at': '{{runtime}}, running from {{origin}} at {{path}}.';
			};
			'settings-file': {
				description: '{{provider}} reads its own configuration from this file. Ensemblr never edits it — open it in your editor to change permissions, hooks, or MCP servers.';
				label: '{{provider}} settings file';
				'menu-aria-label': '{{label}} — choose an app';
				open: 'Open in';
				'primary-aria-label': '{{label}} {{app}}';
			};
			'sign-in-hint': 'Sign-in is interactive: Ensemblr copies the command, you run it in a terminal.';
			status: {
				checking: 'Checking…';
				connected: 'Connected';
				'not-ready': 'Not ready';
				unavailable: 'Unavailable';
			};
			'tabs-aria-label': 'Agent providers';
			title: 'Providers';
		};
		repo: {
			actions: {
				'branch-rename-description': 'Custom instructions for generating branch names from your messages.';
				'branch-rename-title': 'Branch rename preferences';
				'code-review-description': 'Add custom instructions sent to the agent when you click the Review button.';
				'code-review-title': 'Code review preferences';
				'create-pr-description': 'Add custom instructions sent to the agent when you click the Create PR button.';
				'create-pr-title': 'Create PR preferences';
				description: 'Configure action-specific behavior and instructions for this repository.';
				'fix-errors-description': 'Add custom instructions sent to the agent when you click the Fix errors button.';
				'fix-errors-title': 'Fix errors preferences';
				'general-description': 'A master prompt prepended as context to the first message of every new chat in this repository.';
				'general-title': 'General preferences';
				placeholder: 'Add your preferences here. The agent will be told to prioritize these instructions over its default instructions.';
				'remove-aria-label': 'Remove {{name}}';
				'resolve-conflicts-description': 'Add custom instructions sent to the agent when you click the Resolve conflicts button.';
				'resolve-conflicts-title': 'Resolve conflicts preferences';
				title: 'Actions';
			};
			'archive-on-merge': {
				description: 'Automatically archive a workspace after merging its PR. Overrides your user-scope default for this repo.';
				label: 'Archive on merge';
			};
			'archive-script': {
				description: 'Runs before a workspace is archived.';
				label: 'Archive script';
				placeholder: 'e.g. rm -rf node_modules';
			};
			'auto-run': {
				description: "Start this repository's run script automatically after a new local workspace finishes setup.";
				label: 'Auto-run after setup';
			};
			'branch-from': {
				description: 'Each workspace is an isolated copy of your codebase. Set the upstream branch new workspaces fork from.';
				label: 'Branch new workspaces from';
				'repository-default': 'Repository default';
				'search-placeholder': 'Search or enter a ref…';
			};
			'delete-branch': {
				description: 'Delete the local branch when archiving a workspace. Overrides your user-scope default for this repo.';
				label: 'Delete branch on archive';
			};
			environment: {
				description: 'Repository-scoped environment variables. Repository values override user defaults; secrets are stored in the macOS Keychain.';
				title: 'Environment';
			};
			'files-to-copy': {
				description: 'Ensemblr will automatically copy these file paths into each new workspace. Supports gitignore-style globs.';
				label: 'Files to copy';
			};
			git: {
				'committed-note': 'Committed <file>.ensemblr/settings.toml</file> values shared with the team still win over these personal overrides.';
				description: 'Per-repository git defaults. These override your user-scope git settings for this repo only.';
				title: 'Git';
			};
			misc: {
				description: 'Repository paths, preview URLs, files-to-copy patterns, and lifecycle.';
				title: 'Misc';
			};
			'not-found': 'Repository <id>{{repoId}}</id> not found.';
			'preview-urls': {
				add: '+ Add preview URL';
				description: 'Overrides the terminal panel’s Open button URL. Add more than one to switch between them from the Open button dropdown; the first is opened by default and the rest appear in the dropdown in order. Supports `$ENSEMBLR_WORKSPACE_NAME` and `$ENSEMBLR_PORT`. Leave blank to auto-detect from output logs.';
				label: 'Preview URLs';
				'name-aria-label': 'Preview URL name';
				'name-placeholder': 'Name';
				'template-aria-label': 'Preview URL template';
			};
			'remote-origin': {
				description: 'Where Ensemblr pushes, pulls, and opens PRs. Read-only for now — runtime honors the git "origin" remote; a configurable remote is planned.';
				label: 'Remote origin';
			};
			remove: {
				description: 'Removes the repository from Ensemblr. The on-disk directory at<path>{{path}}</path>is not deleted; delete it manually if you want it gone.';
				title: 'Remove this repository?';
				trigger: 'Remove repository';
			};
			'root-path': {
				description: 'Do not move or delete this directory. Instead, remove the repository in Ensemblr.';
				label: 'Root path';
			};
			'run-mode': {
				concurrent: 'Concurrent';
				'concurrent-description': 'Run scripts can run in multiple workspaces at once.';
				description: 'Whether run scripts can run in parallel across workspaces.';
				label: 'Run mode';
				nonconcurrent: 'Non-concurrent';
				'nonconcurrent-description': 'Only one run script can run at a time.';
			};
			scripts: {
				description: 'Commands that run when workspaces are set up, run, or archived. Saved to the repository’s committed .ensemblr/settings.toml.';
				diverges: 'The workspace you have open commits different scripts on its branch, and runs those. Merge this file to change what it runs.';
				title: 'Scripts';
			};
			'setup-script': {
				description: 'Runs when a new workspace is created.';
				label: 'Setup script';
				placeholder: 'e.g. npm ci';
			};
			spotlight: {
				'coming-soon': 'Coming soon';
				description: 'Replace Run with Spotlight for this repository so workspace changes are tested in the repository root. Spotlight is a separate feature still in development (workspace→root diff/apply with rollback); see docs/product/discovery-spotlight-testing.md.';
				label: 'Use spotlight testing';
			};
			'workspaces-path': {
				description: 'Do not move or delete the workspace subdirectories. Instead, archive workspaces in Ensemblr.';
				label: 'Workspaces path';
			};
		};
		'repo-nav': {
			actions: 'Actions';
			empty: 'No repository selected.';
			environment: 'Environment';
			git: 'Git';
			misc: 'Misc';
			scripts: 'Scripts';
		};
		'run-scripts': {
			description: "Shortcuts for quick actions, like running your dev server or test suite. Use <port>$ENSEMBLR_PORT</port> for the workspace's allocated port.";
			editor: {
				'add-title': 'Add run script';
				command: 'Command';
				default: 'Default';
				'default-description': 'Runs when you press ⌘R in a workspace that has no other pick.';
				description: "Shortcuts for quick actions, like running your dev server or test suite. Use <port>$ENSEMBLR_PORT</port> for this workspace's allocated port.";
				'duplicate-name': 'Another run script already uses this name.';
				'edit-title': 'Edit run script';
				name: 'Name';
			};
			empty: 'No run scripts yet. Add one to get started.';
			'icon-picker': {
				'no-matches': 'No icons match “{{query}}”.';
				search: 'Search icons';
				'trigger-aria-label': 'Icon: {{name}}';
			};
			row: {
				default: 'Default';
				'delete-aria-label': 'Delete {{name}}';
				'edit-aria-label': 'Edit {{name}}';
				unavailable: 'Not available locally';
			};
			title: 'Run scripts';
		};
		'source-badge': {
			'built-in-default': 'default';
			'config-default': 'config defaults';
			'managed-config': 'managed config';
			sqlite: 'personal (sqlite)';
			unset: 'not set';
			'user-default': 'user defaults';
			value: 'source: {{source}}';
			'value-locked': 'source: {{source}} · locked';
		};
	};
	workbench: {
		'add-project': {
			check: {
				'not-ready': '{{title}} is not ready yet.';
			};
			'open-github': {
				label: 'Open GitHub project';
				unavailable: 'Sign in with the GitHub CLI (gh auth login) to open GitHub projects.';
			};
			'open-local': {
				label: 'Open local project';
				unavailable: 'Set a writable Ensemblr root directory before opening local projects.';
			};
			'quick-start': {
				label: 'Quick start';
				unavailable: 'Set a writable Ensemblr root directory before starting a new project.';
			};
		};
		'all-files': {
			empty: {
				message: 'Files appear here as soon as they are created.';
				title: 'No files yet';
			};
			'open-preview': 'Open {{path}} preview';
		};
		'all-files-search': {
			description: 'Open a repository file from the All files tab.';
			empty: 'No files match your search.';
			'group-files': 'Files';
			placeholder: 'Search files';
			title: 'Search files';
		};
		'archive-repository': {
			cleanup: {
				description: 'The per-workspace <0>.context/</0> handoff files are preserved; anything else not pushed will be lost.';
				label: 'Also remove each worktree and drop its local branch';
			};
			description: "Marks the repository and {{workspaces}} as archived. Each workspace's <0>.context/</0> handoff files are preserved under <1>archived-contexts/</1>. Worktrees and the repository folder stay on disk.";
			title: 'Archive repository?';
		};
		'archive-workspace': {
			cleanup: {
				description: 'The <0>.context/</0> handoff files are preserved; anything else not pushed to the remote will be lost.';
				label: 'Also remove the worktree and drop the local branch';
			};
			description: 'Marks the workspace as archived and preserves its <0>.context/</0> handoff files under <1>archived-contexts/</1>. By default the worktree folder and local branch stay on disk; nothing is committed or pushed.';
			title: 'Archive workspace?';
		};
		'attachment-menu': {
			'add-attachment': 'Add attachment';
			'aria-label': 'Attachments';
			'link-issue': 'Link issue';
			'link-issue-soon': {
				title: 'Linking issues is coming soon.';
			};
			'link-workspaces': 'Link workspaces';
			'link-workspaces-soon': {
				title: 'Linking workspaces is coming soon.';
			};
			tooltip: 'Add attachments, link issues, and more';
		};
		autocomplete: {
			'no-commands': 'No matching commands';
			'no-files': 'No matching files';
		};
		'browse-archive': {
			description: 'Restore an archived workspace, or permanently purge it. Restoring rebuilds the worktree from the recorded base branch when branch cleanup ran at archive time.';
			empty: {
				failed: 'Failed to load archived workspaces.';
				loading: 'Loading archived workspaces…';
				none: 'No archived workspaces for this repository.';
				unavailable: 'The preload bridge is unavailable in this context.';
			};
			row: {
				archived: 'Archived {{date}}';
				'archived-destroyed': 'Archived {{date}} · worktree was destroyed (recreate from base branch on restore)';
				'delete-permanently': 'Delete permanently';
				'no-branch': 'no branch';
			};
			title: 'Workspace archive — {{repository}}';
		};
		'checks-panel': {
			blocked: {
				detail: 'Resolve blockers before merge.';
				title: 'Checks failed';
			};
			checking: {
				detail: 'Checks are still running.';
				title: 'Checks pending';
			};
			empty: {
				detail: 'No local changes to review.';
			};
			'no-pull-request': {
				title: 'No pull request';
			};
			open: {
				detail: 'Pull request is open.';
				title: 'Pull request #{{number}}';
			};
			ready: {
				detail: 'All required checks passed.';
				title: 'Ready to merge';
			};
			uncommitted: {
				detail_one: '{{count}} uncommitted change ready for PR setup.';
				detail_other: '{{count}} uncommitted changes ready for PR setup.';
			};
			working: {
				detail: 'The agent is updating this workspace.';
				title: 'Pull request active';
			};
		};
		'close-running-chat': {
			confirm: 'Close anyway';
			description: 'This chat is currently running. Closing it will stop the current agent session.';
			title: 'Close running chat?';
		};
		'closed-tabs': {
			empty: 'No closed chat tabs';
			tooltip: 'Closed chat tabs';
			trigger: 'Open closed chat tabs';
		};
		'command-palette': {
			empty: 'No matching command.';
			'go-history': 'Open chat history';
			'go-home': 'Go to workbench';
			'go-linear': 'Browse Linear issues';
			'group-appearance': 'Appearance';
			'group-navigation': 'Navigation';
			'group-settings': 'Settings';
			label: 'Command palette';
			placeholder: 'Search commands…';
			'settings-advanced': 'Settings · Advanced';
			'settings-appearance': 'Settings · Appearance';
			'settings-diagnostics': 'Settings · Diagnostics';
			'settings-environment': 'Settings · Environment';
			'settings-experimental': 'Settings · Experimental';
			'settings-general': 'Settings · General';
			'settings-git': 'Settings · Git';
			'settings-integrations': 'Settings · Integrations';
			'settings-models': 'Settings · Models';
			'settings-providers': 'Settings · Providers';
			'theme-dark': 'Theme · Dark';
			'theme-light': 'Theme · Light';
			'theme-system': 'Theme · System';
		};
		composer: {
			'aria-label': 'Agent composer';
			'blocked-follow-up': 'Follow-ups are blocked while the agent is working — stop the turn or wait for it to finish.';
			'focus-hint': '<key>{{shortcut}}</key><label>to focus</label>';
			model: {
				pending: 'Model pending';
			};
			placeholder: 'Ask to make changes, @mention files, run /commands';
			'plan-mode': {
				placeholder: 'Describe what you want built — the agent will plan it with you before touching any files';
			};
			ready: {
				placeholder: 'Ask the agent to continue {{session}}';
			};
			'send-tooltip': 'Send message';
			'setup-blocked': {
				placeholder: 'Fix setup blockers before sending a prompt.';
				reason_one: '{{count}} required setup check needs attention.';
				reason_other: '{{count}} required setup checks need attention.';
			};
			'setup-error': {
				placeholder: 'Resolve setup diagnostics before starting an agent turn.';
			};
			'setup-loading': {
				placeholder: 'Setup checks are still loading.';
				reason: 'Ensemblr is still checking setup readiness.';
			};
			thinking: {
				pending: 'Thinking pending';
			};
			'upload-input': {
				'aria-label': 'Upload attachment';
			};
		};
		'context-usage': {
			'aria-label': 'Context usage';
			'gauge-title': 'Context usage gauge';
			heading: 'Context';
			unavailable: 'Context window unavailable for this model.';
			'window-used': 'Window used';
		};
		'control-tool': {
			'add-diff-comments': {
				done: 'Left review comments';
				running: 'Leaving review comments';
			};
			'ask-user-question': {
				done: 'Asked you a question';
				running: 'Asking you a question';
			};
			'close-tab': {
				done: 'Closed a tab';
				running: 'Closing a tab';
			};
			'exit-plan-mode': {
				done: 'Submitted a plan';
				running: 'Submitting a plan';
			};
			'focus-dock-tab': {
				done: 'Focused a terminal';
				running: 'Focusing a terminal';
			};
			'focus-panel': {
				done: 'Focused a panel';
				running: 'Focusing a panel';
			};
			'focus-tab': {
				done: 'Focused a tab';
				running: 'Focusing a tab';
			};
			'get-conversation-status': {
				done: 'Checked a sub-agent';
				running: 'Checking a sub-agent';
			};
			'get-diff-comments': {
				done: 'Read review comments';
				running: 'Reading review comments';
			};
			'get-last-message': {
				done: "Read a sub-agent's report";
				running: "Reading a sub-agent's report";
			};
			'get-workspace-diff': {
				done: 'Read the diff';
				running: 'Reading the diff';
			};
			'get-workspace-status': {
				done: 'Read board status';
				running: 'Reading board status';
			};
			'launch-harness': {
				done: 'Launched a harness';
				running: 'Launching a harness';
			};
			'linear-create-comment': {
				done: 'Commented on a Linear issue';
				running: 'Commenting on a Linear issue';
			};
			'linear-get-issue': {
				done: 'Read a Linear issue';
				running: 'Reading a Linear issue';
			};
			'linear-get-metadata': {
				done: 'Read Linear teams and states';
				running: 'Reading Linear teams and states';
			};
			'linear-list-issues': {
				done: 'Searched Linear issues';
				running: 'Searching Linear issues';
			};
			'linear-update-issue': {
				done: 'Updated a Linear issue';
				running: 'Updating a Linear issue';
			};
			'list-models': {
				done: 'Listed models';
				running: 'Listing models';
			};
			'list-run-scripts': {
				done: 'Listed run scripts';
				running: 'Listing run scripts';
			};
			'list-tabs': {
				done: 'Listed tabs';
				running: 'Listing tabs';
			};
			'list-terminals': {
				done: 'Listed terminals';
				running: 'Listing terminals';
			};
			'list-workspaces': {
				done: 'Listed workspaces';
				running: 'Listing workspaces';
			};
			'notify-orchestrator': {
				done: 'Notified the orchestrator';
				running: 'Notifying the orchestrator';
			};
			'open-tab': {
				done: 'Opened a tab';
				running: 'Opening a tab';
			};
			'read-conversation': {
				done: "Read a sub-agent's transcript";
				running: "Reading a sub-agent's transcript";
			};
			'read-terminal-output': {
				done: 'Read terminal output';
				running: 'Reading terminal output';
			};
			'resolve-diff-comments': {
				done: 'Resolved review comments';
				running: 'Resolving review comments';
			};
			'send-follow-up': {
				done: 'Steered a sub-agent';
				running: 'Steering a sub-agent';
			};
			'set-workspace-status': {
				done: 'Moved the workspace';
				running: 'Moving the workspace';
			};
			'spawn-chat-tab': {
				done: 'Opened a chat tab';
				running: 'Opening a chat tab';
			};
			'start-conversation': {
				done: 'Started a sub-agent';
				running: 'Starting a sub-agent';
			};
			'start-terminal': {
				done: 'Started a terminal';
				running: 'Starting a terminal';
			};
			'stop-terminal': {
				done: 'Stopped a terminal';
				running: 'Stopping a terminal';
			};
			'wait-for-agents': {
				done: 'Waited for sub-agents';
				running: 'Waiting for sub-agents';
			};
			'with-detail': '{{action}}: {{detail}}';
			'write-terminal': {
				done: 'Typed into a terminal';
				running: 'Typing into a terminal';
			};
		};
		'create-workspace-source': {
			description: 'Choose a branch, pull request, or issue to start a workspace.';
			loading: 'Loading {{sources}}…';
			'no-match': 'No {{sources}} match your search.';
			repository: {
				empty: 'No repositories found.';
				search: 'Search repositories…';
				select: 'Select repository';
			};
			search: {
				branch: 'Search by name';
				issue: 'Search by issue number, title, or description';
				'pull-request': 'Search by title, number, or author';
			};
			title: 'Create workspace from source';
		};
		dashboard: {
			card: {
				'pull-request-aria': 'Pull request #{{number}} {{state}}';
				state: {
					branch: 'branch';
					'pr-blocked': 'blocked';
					'pr-checking': 'checks running';
					'pr-merged': 'merged';
					'pr-open': 'open';
					'pr-ready': 'ready to merge';
					'pr-working': 'agent working';
					'workspace-blocked': 'workspace blocked';
					'workspace-checking': 'workspace checks running';
					'workspace-working': 'agent working';
				};
			};
			column: {
				'aria-label': '{{status}} column, {{workspaces}}';
			};
			title: 'Dashboard';
		};
		'delete-repository': {
			description: "Permanently removes the repository and {{workspaces}} from Ensemblr. Each workspace's worktree folder is deleted and its local branch is dropped. The repository folder stays on disk so you can re-register it later. This cannot be undone.";
			title: 'Delete repository?';
		};
		'delete-workspace': {
			description: 'Permanently removes the worktree folder, drops the local branch, and deletes the workspace from Ensemblr. Anything not pushed to the remote is lost. This cannot be undone.';
			title: 'Delete workspace?';
		};
		'diff-comment': {
			author: {
				agent: 'Agent';
			};
		};
		'dock-panel': {
			'close-tab': 'Close {{label}} tab';
			collapse: 'Collapse terminal area';
			expand: 'Expand terminal area';
			'new-terminal': 'New terminal';
		};
		'dock-tab': {
			run: {
				label: 'Run';
			};
			setup: {
				label: 'Setup';
			};
		};
		'file-preview': {
			actions: {
				'show-preview': 'Show formatted preview';
				'show-source': 'Show raw source';
				'wrap-off': 'Disable word wrap';
				'wrap-on': 'Enable word wrap';
			};
			empty: {
				loading: 'Loading {{filePath}}…';
				'no-file': 'This tab has no file associated with it.';
			};
			failure: {
				'invalid-cwd': 'The workspace directory is unavailable.';
				'invalid-path': '{{filePath}} is outside this workspace.';
				'not-file': '{{filePath}} is a directory and cannot be previewed.';
				'not-found': '{{filePath}} does not exist in this workspace.';
				'too-large': '{{filePath}} is too large to preview.';
				unreadable: 'Could not read {{filePath}}.';
			};
			'image-alt': 'Preview of {{filePath}}';
		};
		'file-tree': {
			'collapse-folder': 'Collapse {{path}}';
			'expand-folder': 'Expand {{path}}';
		};
		'file-tree-menu': {
			actions: '{{path}} actions';
		};
		'git-failure': {
			'invalid-cwd': {
				message: 'The folder this workspace points at could not be opened. It may have been moved, renamed, or deleted since the workspace was created.';
				title: 'Workspace folder unavailable';
			};
			'merge-probe': {
				title: 'Could not check for merge conflicts';
			};
			'not-a-repo': {
				message: 'This folder is not tracked by git, so there is no history to compare against. Initialize a repository here, or recreate the workspace from a cloned one.';
				title: 'Not a git repository';
			};
			unknown: {
				message: 'Git could not report this workspace’s changes.';
				title: 'Could not read changes';
			};
		};
		'harness-launcher': {
			'none-detected': 'No harnesses detected';
			'none-installed': 'No coding agents detected';
			trigger: 'Launch coding agent';
		};
		header: {
			'review-sidebar': {
				collapse: 'Collapse review sidebar';
				open: 'Open review sidebar';
			};
			'target-branch': {
				placeholder: 'Set target branch';
				search: 'Search or enter a branch…';
				tooltip: 'Target branch — what this workspace diffs and opens pull requests against.';
			};
		};
		health: {
			checking: {
				detail: 'Renderer is calling the typed preload bridge through TanStack Query.';
				label: 'Checking IPC';
			};
			'config-blocked': {
				detail: 'Declarative config blocks readiness.';
				label: '{{appName}} config requires attention';
			};
			'database-error': {
				detail: 'Database failed to open.';
				label: '{{appName}} database unavailable';
			};
			'no-bridge': {
				detail: 'Electron preload bridge is unavailable in this context.';
			};
			online: {
				detail: 'Electron {{electronVersion}} on {{platform}}. Database schema v{{schemaVersion}}.';
				label: '{{appName}} IPC online';
			};
			'setup-blocked': {
				detail_one: '{{count}} required setup check needs attention.';
				detail_other: '{{count}} required setup checks need attention.';
				label: 'Setup blocked';
			};
			'setup-checking': {
				label: 'Setup checks pending';
			};
			'setup-error': {
				label: 'Setup diagnostics unavailable';
			};
			'setup-loading': {
				detail: 'Ensemblr is collecting setup readiness checks.';
				label: 'Checking setup';
			};
			unavailable: {
				label: 'IPC unavailable';
			};
		};
		history: {
			bucket: {
				today: 'Today';
				unknown: 'Unknown';
				yesterday: 'Yesterday';
			};
			empty: {
				failed: 'Failed to load workspace history.';
				loading: 'Loading workspaces…';
				'no-match': 'No workspaces match your filter.';
				none: 'No workspaces yet.';
				unavailable: 'The preload bridge is unavailable in this context.';
			};
			filter: {
				label: 'Filter workspaces';
				placeholder: 'Filter workspaces…';
			};
			row: {
				'go-to': 'Go to';
				'restore-blocked': 'Cannot restore: the recorded base branch or branch name is missing.';
			};
		};
		'landing-card': {
			'aria-label': 'Workspace landing summary';
			branch: {
				plain: 'On <ref>{{branchName}}</ref>';
				'with-base': 'On <ref>{{branchName}}</ref>, compared against <ref>{{baseBranch}}</ref>';
			};
			created: {
				copied_one: 'Created {{workspaceName}} and copied {{count}} file';
				copied_other: 'Created {{workspaceName}} and copied {{count}} files';
				detail: 'Created {{workspaceName}}. {{detail}}';
			};
			headline: 'You’re in a new copy of <repo>{{repositoryName}}</repo> called <workspace>{{workspaceName}}</workspace>';
		};
		'lifecycle-dialog': {
			summary: {
				branch: 'Branch';
				path: 'Path';
				repository: 'Repository';
				workspace: 'Workspace';
			};
		};
		'mcp-servers': {
			'aria-label': 'MCP servers';
			authorise: 'Authorise {{name}}';
			empty: 'No MCP servers are configured.';
			heading: 'MCPs';
			loading: 'Reading the MCP roster…';
			refresh: 'Refresh MCP servers';
			status: {
				disabled: 'Disabled';
				failed: 'Error';
				'needs-auth': 'Needs auth';
				pending: 'Awaiting status';
			};
		};
		'model-picker': {
			'all-hidden': 'All models hidden — manage in Settings → Models.';
			'aria-label': 'Model';
			favourite: 'Favourite model';
			group: {
				favourites: 'Favourites';
			};
			'locked-hint': 'This chat runs on {{provider}}. Start a new chat to switch provider.';
			pending: 'Model pending';
			tooltip: 'Change model';
			unfavourite: 'Unfavourite model';
			unselected: 'Select model';
		};
		'navigation-sidebar': {
			footer: {
				repositories_one: '{{count}} repo';
				repositories_other: '{{count}} repos';
				workspaces_one: '{{count}} workspace';
				workspaces_other: '{{count}} workspaces';
			};
			nav: {
				dashboard: 'Dashboard';
				history: 'History';
				settings: 'Settings';
				'settings-aria': 'Open app settings';
			};
			pinned: {
				label: 'Pinned';
			};
			repositories: {
				label: 'Repositories';
			};
			repository: {
				reorder: 'Reorder repository {{repository}}';
			};
			setup: {
				blocked_one: '{{count}} setup check blocked — open diagnostics';
				blocked_other: '{{count}} setup checks blocked — open diagnostics';
				checking: 'Setup checks running…';
				'not-ready': 'Setup not ready — open diagnostics';
			};
		};
		'new-chat': {
			'aria-label': 'New chat empty state';
			headline: 'New chat in <path>/{{workspaceName}}</path>.';
			'transcripts-label': 'Add chat transcripts:';
			'untitled-transcript': 'Untitled transcript';
		};
		'open-in': {
			'copy-path': 'Copy path';
			label: 'Open in';
		};
		'open-workspace-menu': {
			options: 'Open current workspace app options';
			primary: 'Open current workspace in {{target}}';
		};
		'permission-boundary': {
			allowed: 'Allowed';
			blocked: 'Blocked';
			'confirmation-required': 'Requires confirmation';
		};
		'pi-replay': {
			summary: {
				file: 'file';
				'shell-command': 'shell command';
			};
		};
		placeholder: {
			dashboard: {
				detail: 'Kanban board is not connected yet.';
				title: 'Dashboard';
			};
			history: {
				detail: 'Session history is not connected yet.';
				title: 'History';
			};
			linear: {
				detail: 'Linear issues are available from the Linear route.';
				title: 'Linear';
			};
			settings: {
				detail: 'Settings are available from the settings route.';
				title: 'Settings';
			};
			setup: {
				detail: 'Complete setup checks before creating or opening workspaces.';
				title: 'Setup required';
			};
		};
		'plan-mode': {
			'aria-label-off': 'Plan mode: off. Click to toggle.';
			'aria-label-on': 'Plan mode: on. Click to toggle.';
			chip: 'Plan';
			'tooltip-off': 'Plan before editing';
			'tooltip-on': 'Leave plan mode';
		};
		'plan-review': {
			actions: {
				'hand-off': 'Hand off';
				refine: 'Refine';
			};
			'aria-label': 'Plan review';
		};
		preview: {
			'choose-url': 'Choose preview URL';
			'open-named': 'Open {{name}}';
			'open-port': 'Open preview on port {{port}}';
			'open-port-label': 'Open :{{port}}';
		};
		'preview-deployment': {
			label: 'Preview';
		};
		'preview-url': {
			fallback: {
				name: 'Preview {{index}}';
			};
		};
		'project-avatar': {
			alt: '{{owner}} avatar';
		};
		'project-creation-menu': {
			recents: 'Recents';
			trigger: 'Open repository creation menu';
		};
		provider: {
			local: 'Local';
			preview: 'Preview';
		};
		'raw-frames': {
			'aria-label': 'Pi raw frames debug panel';
			clear: 'Clear frames';
			close: 'Close debug panel';
			'copied-aria': 'Copied frame to clipboard';
			'copied-title': 'Copied';
			'copy-aria': 'Copy frame';
			'copy-title': 'Copy frame (signatures follow the current toggle)';
			'count-title': 'visible / total captured';
			heading: 'Pi raw frames';
			'hide-session-stats': 'hide session_stats';
			'hide-signatures': 'hide signatures';
			'kind-label': 'kind:';
			'kind-other': 'other';
			'noise-label': 'noise:';
			'session-scope': 'Toggle session scope';
			'this-session': 'this session';
			waiting: 'Waiting for Pi traffic…';
		};
		'rename-workspace': {
			branch: {
				hint: 'Follows the workspace name slug until you edit it.';
				label: 'Branch name';
				'pinned-hint': 'This branch came from a branch or pull request the workspace took over, so renaming it here would orphan that work.';
			};
			description: 'Updates the workspace name. The branch is auto-renamed from the slugged name unless you override it below. The worktree folder stays put.';
			'description-pinned': 'Updates the workspace name. This workspace took over an existing branch, so the branch keeps its name. The worktree folder stays put.';
			name: {
				label: 'Workspace name';
			};
			title: 'Rename workspace';
		};
		'repository-header': {
			collapse: 'Collapse repository {{repository}}';
			'create-from-source': 'Create workspace from a source in {{repository}}';
			'create-workspace': 'Create workspace in {{repository}}';
			'creating-workspace': 'Creating workspace in {{repository}}';
			expand: 'Expand repository {{repository}}';
			settings: 'Repository settings for {{repository}}';
		};
		'repository-menu': {
			archive: 'Archive repository';
			'aria-label': '{{repository}} repository actions';
			'create-from': 'Create from…';
			delete: 'Delete repository…';
			'new-workspace': 'New workspace';
			settings: 'Repository settings';
			'workspace-archive': 'Workspace archive';
		};
		'restore-checkpoint': {
			confirm: 'Restore workspace';
			description: 'Workspace files revert to the snapshot taken before “{{label}}”. Later messages in this chat are hidden from the timeline, but the agent’s own session history is never modified — you can keep prompting from the restored state.';
			'other-sessions': 'Another chat session is active in this workspace; its newer file changes may be overwritten by this restore.';
			title: 'Restore workspace to before this turn?';
			untracked: 'Files created after the snapshot that were never tracked stay in place.';
		};
		'run-script': {
			choose: 'Choose run script';
			'configure-action': 'Setup Scripts';
			empty: {
				detail: 'Add a run script for the normal dev server, watcher, worker, or local app command.';
				title: 'No run script configured';
			};
			'run-label': 'Run {{script}}';
			start: 'Start Run';
			'stop-label': 'Stop run script';
			'stopped-caption': 'Test your changes here.';
		};
		'session-tab': {
			placeholder: {
				label: 'Workspace';
				summary: 'Workspace session placeholder.';
				updated: 'loaded';
			};
			snapshot: {
				summary: 'SQLite workspace record loaded. Agent sessions are not wired yet.';
			};
		};
		'session-tabs': {
			'close-tab': 'Close {{label}} tab';
			debug: {
				hide: 'Hide Pi debug panel';
				show: 'Show Pi debug panel';
				title: 'Pi raw frames (debug)';
				toggle: 'Toggle Pi debug panel';
			};
			'new-tab': 'New chat tab';
		};
		'setup-script': {
			'add-manually': 'Add manually';
			'ask-agent': 'Ask agent';
			missing: {
				message: 'Run commands when a workspace is created to install dependencies or set up the environment';
				title: 'Add setup script';
			};
			'not-run': {
				message: 'Setup script output will appear here after running setup.';
				title: 'No setup script output';
			};
			rerun: 'Rerun setup';
			run: 'Run setup';
			stop: 'Stop setup';
		};
		'shell-title': {
			'build-image': 'Building an image';
			'build-project': 'Building the project';
			'change-directory': 'Changing directory';
			'change-permissions': 'Changing permissions';
			'check-code': 'Checking the code';
			'check-directory': 'Checking the directory';
			'check-disk-usage': 'Checking disk usage';
			'check-git-status': 'Checking git status';
			'commit-changes': 'Committing changes';
			'compare-files': 'Comparing files';
			'copy-files': 'Copying files';
			'count-lines': 'Counting lines';
			'create-directory': 'Creating a directory';
			'create-file': 'Creating a file';
			'fetch-remote': 'Fetching from the remote';
			'fetch-url': 'Fetching a URL';
			'inspect-processes': 'Inspecting processes';
			'install-dependencies': 'Installing dependencies';
			'list-branches': 'Listing branches';
			'list-files': 'Listing files';
			'locate-binary': 'Locating a binary';
			'merge-branches': 'Merging branches';
			'move-files': 'Moving files';
			'open-file': 'Opening a file';
			'print-output': 'Printing output';
			'pull-changes': 'Pulling changes';
			'push-changes': 'Pushing changes';
			'read-commit': 'Reading a commit';
			'read-file': 'Reading a file';
			'read-git-history': 'Reading git history';
			'rebase-branch': 'Rebasing the branch';
			'remove-files': 'Removing files';
			'review-changes': 'Reviewing changes';
			'run-container': 'Running a container';
			'run-named': 'Running {{name}}';
			'run-script': 'Running a script';
			'run-tests': 'Running tests';
			'search-files': 'Searching files';
			'stage-changes': 'Staging changes';
			'start-dev-server': 'Starting the dev server';
			'stash-changes': 'Stashing changes';
			'stop-process': 'Stopping a process';
			'switch-branches': 'Switching branches';
			'transform-text': 'Transforming text';
			'type-check': 'Type-checking';
			waiting: 'Waiting';
		};
		'sidebar-header': {
			agent: {
				working: 'Working...';
			};
			pr: {
				merged: 'Merged';
				ready: 'Ready to merge';
			};
		};
		'sub-agent-status': {
			'aria-label': 'Sub-agent runtime';
		};
		terminal: {
			'session-ended': 'Session ended.';
			'session-failed': 'Session failed.';
			'session-stopped': 'Session stopped.';
		};
		'thinking-picker': {
			'aria-label-effort': 'Effort level: {{level}}. Click to cycle.';
			'aria-label-thinking': 'Thinking level: {{level}}. Click to cycle.';
			'icon-title': 'Thinking level';
			off: 'Off';
			'pending-effort': 'Effort pending';
			'pending-thinking': 'Thinking pending';
			'tooltip-effort': 'Adjust effort level';
			'tooltip-thinking': 'Adjust thinking level';
		};
		timeline: {
			'aria-label': 'Agent session timeline';
			'load-failed': 'Could not load timeline events.';
			'runtime-error': 'Runtime error';
			starting: {
				agent: 'Starting agent';
				loading: 'Loading conversation';
			};
			'turn-stopped': 'You stopped this turn';
		};
		'tool-call': {
			bash: {
				title: 'Bash';
			};
			diagnostics: {
				clean: 'Diagnostics';
				count_one: '{{count}} diagnostic';
				count_other: '{{count}} diagnostics';
				none: 'No diagnostics';
			};
			edit: {
				title: 'Edit';
			};
			failed: {
				generic: 'Tool execution failed.';
				title: '{{tool}} failed';
				unspecified: 'The call failed without a reported reason.';
			};
			generic: {
				'input-label': 'Input:';
				'output-label': 'Output:';
				title: 'Tool';
			};
			glob: {
				title: 'Glob';
			};
			grep: {
				title: 'Search';
			};
			list: {
				title: 'List';
			};
			placeholder: {
				'empty-pattern': '(empty)';
				'no-command': '(no command)';
				'no-path': '(no path)';
			};
			read: {
				image: 'Read image';
				lines_one: 'Read {{count}} line';
				lines_other: 'Read {{count}} lines';
				title: 'Read';
			};
			reasoning: {
				title: 'Thinking';
			};
			skill: {
				named: 'Skill: {{name}}';
				title: 'Skill';
			};
			write: {
				title: 'Write';
			};
		};
		'turn-diff': {
			empty: {
				failed: 'Could not compute diff.';
				loading: 'Computing turn diff…';
				'no-changes': 'No file changes in this turn.';
				'no-turn': 'This tab has no turn associated.';
			};
			'file-count_one': '{{count}} file';
			'file-count_other': '{{count}} files';
		};
		'workspace-checks': {
			blocked: {
				detail: 'Checks are failing.';
				label: 'Checks failed';
			};
			checking: {
				detail: 'Checks are running.';
				label: 'Checks running';
			};
			closed: {
				detail: 'Pull request closed.';
				label: 'Closed';
			};
			creating: {
				detail: 'The workspace is still being created.';
				label: 'Creating';
			};
			merged: {
				detail: 'Pull request merged.';
				label: 'Merged';
			};
			none: {
				detail: 'No checks reported.';
				label: 'No checks';
			};
		};
		'workspace-item': {
			'archive-aria': 'Archive workspace {{workspace}}; {{boundary}}';
			creating: 'Creating workspace…';
			'creating-aria': 'Workspace {{workspace}} is being created';
			'creating-tooltip': '{{workspace}} is being created';
			'dock-activity': 'Dock activity running';
			'open-aria': 'Open workspace {{workspace}}';
			'open-busy-aria': 'Open workspace {{workspace}}; dock activity running';
		};
		'workspace-landing': {
			'branch-source': {
				base: 'Changes are compared against {{branch}}.';
				default: 'Changes are compared against the repository default branch.';
			};
			'copied-files': {
				detail_one: 'Copied {{count}} file into workspace.';
				detail_other: 'Copied {{count}} files into workspace.';
				unavailable: 'Workspace file count is unavailable.';
			};
			headline: {
				'cloned-repo': 'Repository cloned';
				'linked-issue': 'Workspace created from {{reference}}';
				'new': 'New workspace ready';
			};
			'setup-guidance': {
				missing: 'No setup script is configured for this repository. Add one to bootstrap dependencies before the first agent turn.';
			};
		};
		'workspace-menu': {
			'aria-label': '{{workspace}} workspace actions';
			'mark-read': 'Mark as read';
			'mark-unread': 'Mark as unread';
			'set-status': 'Set status';
		};
		'workspace-pull-request': {
			absent: {
				detail: 'No pull request for this branch yet.';
				label: 'No PR';
			};
			clean: {
				label: 'No PR open';
			};
			present: {
				detail: 'Pull request status from the last GitHub sync.';
			};
		};
		'workspace-rename': {
			succeeded: 'Renamed to {{name}} on branch {{branch}}.';
		};
		'workspace-source': {
			creating: 'creating workspace';
			'default-branch': 'repository default branch {{branch}}';
			fallback: 'workspace loaded from SQLite';
			targets: 'targets {{branch}}';
		};
		'workspace-source-picker': {
			action: {
				'duplicate-branch': 'Duplicate branch';
				'use-branch': 'Use branch';
			};
			kind: {
				branch: 'Branches';
				issue: 'Issues';
				'pull-request': 'Pull requests';
			};
		};
	};
}
