// Generated by `npm run i18n:types` (i18next-cli), then hand-adjusted — the
// `defaultNS` tuple below is deliberate and re-applying the generator will
// overwrite it. See the note on that field before regenerating.
import type Resources from './resources';

declare module 'i18next' {
	interface CustomTypeOptions {
		enableSelector: false;
		// The runtime `defaultNS` is `'common'` (see lib/i18n/instance.ts). It is
		// widened to the full namespace tuple *for typing only* so `ParseKeys`
		// spans every namespace: with a single default namespace, i18next's types
		// drop the plural base key (`t('git:…todos-open', { count })`) and the
		// `ns:`-prefixed form of `<Trans i18nKey>`, both of which this codebase
		// uses everywhere. Keys are always written with their `ns:` prefix, so the
		// extra unprefixed forms this admits are unreachable by convention and
		// `npm run i18n:lint` flags them.
		defaultNS: [
			'common',
			'settings',
			'workbench',
			'review',
			'git',
			'linear',
			'errors',
		];
		resources: Resources;
	}
}
