import { IPC_CHANNELS } from '../../shared/ipc/channels.ts';
import type { PermissionActionKind } from '../../shared/permissions.ts';

/** Preload handle naming one IPC channel, as keyed by {@link IPC_CHANNELS}. */
export type IpcChannelKey = keyof typeof IPC_CHANNELS;

/**
 * The permission action every IPC channel is classified as, or `null` when the
 * channel reads, observes, or stops work and therefore needs no gate.
 *
 * This is the single enforcement list for the renderer's IPC surface: the gate
 * consults it per registration rather than each handler group opting in, which
 * is what let terminal, script, checkpoint, and git writes run ungated. Typing
 * it as a total record over {@link IPC_CHANNELS} makes a new channel a compile
 * error until somebody classifies it.
 *
 * Stop, cancel, and close channels are deliberately `null`: they only ever
 * reduce what is running, and blocking them under `read-only` would strand a
 * process the user is trying to end. `updateRepositorySettings` is `null` for a
 * different reason — it carries the permission mode itself, so its handler runs
 * a bespoke confirmation rather than a mode-derived gate that a read-only
 * repository would use to lock the user out of its own Security screen.
 */
export const IPC_PERMISSION_ACTIONS = {
	architectureSnapshotChanged: null,
	getArchitectureSnapshot: null,
	archiveWorkspace: 'workspace-archive-delete',
	appSettingsChanged: null,
	configChanged: null,
	getAppSettings: null,
	updateAppSettings: 'app-settings-change',
	openAppConfigFile: null,
	getSystemLanguages: null,
	openExternal: null,
	bindAgentSessionToChatTab: null,
	menuCommand: null,
	menuContext: null,
	menuBarChanged: null,
	getMenuBar: null,
	invokeMenuBarItem: null,
	agentControlFocusView: null,
	agentControlTabsChanged: null,
	agentControlReviewCommentsChanged: null,
	agentControlBoardStatus: null,
	agentControlReportBoardStatus: null,
	agentControlAskUserQuestion: null,
	agentControlAskUserQuestionClosed: null,
	agentControlAnswerUserQuestion: null,
	agentControlReviewBriefRequested: null,
	agentControlReviewBriefReply: null,
	agentControlExitPlanMode: null,
	agentControlPlanModeChanged: null,
	agentControlAfkModeChanged: null,
	setAgentPlanMode: null,
	agentSessionEvent: null,
	agentToolApprovalAnswered: null,
	agentToolApprovalClosed: null,
	agentToolApprovalRequested: null,
	activeChatContext: null,
	chatTurnFinished: null,
	focusChatRequested: null,
	focusConciergeRequested: null,
	notificationSoundRequested: null,
	clearConciergeContext: null,
	conciergeContextPressure: null,
	conciergeSessionEvent: null,
	listConciergeArtifacts: null,
	listConciergeEvents: null,
	openConciergeSession: 'workspace-command',
	reportConciergeVisibility: null,
	stopConciergeSession: null,
	submitConciergePrompt: 'workspace-command',
	closeChatTab: null,
	closeWindow: null,
	minimizeWindow: null,
	toggleMaximizeWindow: null,
	windowChromeChanged: null,
	windowMaximizedChanged: null,
	relaunchApp: null,
	cloneGithubRepositoryPrepare: null,
	cloneGithubRepositoryProgress: null,
	cloneGithubRepositoryStart: 'outside-workspace-write',
	closeTerminalSession: null,
	commitWorkspaceChanges: 'workspace-write',
	computeTurnDiff: null,
	confirmRootDirectoryChange: 'root-directory-change',
	continueWorkspaceBranch: 'workspace-write',
	createPullRequest: 'workspace-write',
	createTerminalSession: 'workspace-command',
	createWorkspace: 'workspace-write',
	deleteArchivedWorkspace: 'workspace-archive-delete',
	deleteRepository: 'repository-removal',
	deleteReviewComment: null,
	deleteReviewTodo: null,
	deleteWorkspace: 'workspace-archive-delete',
	clearDictationApiKey: 'app-settings-change',
	dictationKeyStatus: null,
	setDictationApiKey: 'app-settings-change',
	transcribeAudio: null,
	addEnvFile: 'app-settings-change',
	environmentVariables: null,
	listEnvFiles: null,
	readEnvironmentVariableValue: null,
	removeEnvFile: 'app-settings-change',
	selectEnvFile: null,
	setEnvironmentVariable: 'app-settings-change',
	unsetEnvironmentVariable: 'app-settings-change',
	getPullRequestSnapshot: null,
	listAgentHarnesses: null,
	launchAgentHarness: 'workspace-command',
	resumeAgentHarness: 'workspace-command',
	discardWorkspaceChanges: 'workspace-write',
	getWorkspaceCommits: null,
	getWorkspaceFileDiff: null,
	getWorkspaceGitStatus: null,
	getWorkspaceMergeConflicts: null,
	mergePullRequest: 'pull-request-merge',
	pushWorkspaceBranch: 'workspace-write',
	githubRemoteBranchList: null,
	githubOwnerList: null,
	githubRepositoryList: null,
	listRepositoryBranches: null,
	listRepositoryPullRequests: null,
	listRepositoryIssues: null,
	health: null,
	updateStatus: null,
	checkForUpdates: null,
	installUpdate: 'app-settings-change',
	updateStatusChanged: null,
	infisicalAccounts: null,
	infisicalAddAccount: 'app-settings-change',
	infisicalClearLink: 'app-settings-change',
	infisicalLink: null,
	infisicalProjects: null,
	infisicalRemoveAccount: 'app-settings-change',
	infisicalSetLink: 'app-settings-change',
	infisicalSync: null,
	infisicalTestAccount: null,
	initialShellSnapshot: null,
	killTerminalSession: null,
	linearCancelLogin: null,
	linearConnectionStatus: null,
	linearCreateComment: 'outside-workspace-write',
	linearCreateIssue: 'outside-workspace-write',
	linearDisconnect: null,
	linearGetIssue: null,
	linearListIssues: null,
	linearMetadata: null,
	linearStartLogin: null,
	linearUpdateIssue: 'outside-workspace-write',
	listAllChatTabs: null,
	listAllWorkspaces: null,
	listArchivedWorkspaces: null,
	listChatTabs: null,
	forgetLinkedDirectoryRecent: null,
	listLinkedDirectoryRecents: null,
	recordLinkedDirectoryRecent: null,
	selectLinkedDirectory: null,
	listChatTabSummaries: null,
	listAgentModels: null,
	listAgentSessionEvents: null,
	listAgentSessions: null,
	listTurnCheckpoints: null,
	listReviewComments: null,
	listReviewTodos: null,
	listRestorableTerminals: null,
	listTerminalSessions: null,
	listWorkspaceFiles: null,
	listWorkspaceOpenTargets: null,
	openAgentSession: 'workspace-command',
	openChatTab: null,
	openSettingsFileInTarget: null,
	openWorkspaceInTarget: null,
	piRawFrame: null,
	pinChatTab: null,
	quickStartProject: 'outside-workspace-write',
	readWorkspaceDirectory: null,
	readWorkspaceFile: null,
	writeWorkspaceImageAttachment: 'workspace-write',
	writeWorkspaceFileAttachment: 'workspace-write',
	writeWorkspaceActionPrompt: 'workspace-write',
	refreshAgentPlanUsage: null,
	registerLocalRepository: 'outside-workspace-write',
	renameWorkspace: 'workspace-write',
	reorderChatTabs: null,
	restoreChatTab: null,
	restoreCheckpoint: 'workspace-write',
	repositoryConfig: null,
	resizeTerminalSession: null,
	repositoryWorkspaceNavigation: null,
	rootDirectory: null,
	ensureWorkspaceSetup: 'workspace-command',
	addWordToDictionary: null,
	replaceMisspelling: null,
	runTextEditCommand: null,
	textContextMenu: null,
	runWorkspaceScript: 'workspace-command',
	saveReviewComment: null,
	saveReviewTodo: null,
	selectCloneDestination: null,
	setWorkspaceBaseBranch: 'workspace-write',
	selectLocalRepository: null,
	clearAgentProviderExecutablePath: 'app-settings-change',
	getAgentProviderExecutablePath: null,
	getAgentProviderReadiness: null,
	listAgentProviderMcpServers: null,
	listAgentProviderSlashCommands: null,
	openAgentProviderSettingsFile: null,
	setAgentProviderExecutablePath: 'app-settings-change',
	selectAgentProviderExecutable: null,
	selectRootDirectory: null,
	setupDiagnostics: null,
	stopAgentSession: null,
	stopWorkspaceScript: null,
	submitAgentPrompt: 'workspace-command',
	settingsResolution: null,
	sharedRootAdoption: 'root-directory-change',
	terminalLifecycle: null,
	terminalOutput: null,
	terminalSnapshot: null,
	unarchiveWorkspace: null,
	unwatchWorkspaceFiles: null,
	openRepositoryConfigFile: null,
	updateRepositoryScripts: 'workspace-write',
	updateRepositorySettings: null,
	previewSettingsPublication: null,
	applySettingsPublication: 'workspace-write',
	cleanupSettingsPublication: 'workspace-write',
	restoreSettingsPublication: 'workspace-write',
	settingsPublicationRecoveryStatus: null,
	watchWorkspaceFiles: null,
	workspaceFilesChanged: null,
	writeForkSummary: 'workspace-write',
	writeTerminalSession: 'workspace-command',
} as const satisfies Record<IpcChannelKey, PermissionActionKind | null>;

/**
 * Resolves the permission action guarding a channel name (the wire identifier,
 * not the preload handle).
 * @param channel - Wire channel name passed to `ipcMain.handle`.
 * @returns The action to classify, or `null` when the channel needs no gate.
 */
export function permissionActionForChannel(
	channel: string,
): PermissionActionKind | null {
	const key = CHANNEL_KEYS_BY_NAME.get(channel);
	return key ? IPC_PERMISSION_ACTIONS[key] : null;
}

const CHANNEL_KEYS_BY_NAME = new Map<string, IpcChannelKey>(
	Object.entries(IPC_CHANNELS).map(([key, name]) => [
		name,
		key as IpcChannelKey,
	]),
);
