import { randomUUID } from 'node:crypto';

import {
	createIdentityKey,
	createKeychainReference,
	filterMetadata,
	formatLookup,
	maskSecret,
	normalizeFilter,
	normalizeLookup,
	normalizeWriteInput,
} from './normalize.ts';
import {
	type KeychainReference,
	type MockSecretStoreOptions,
	type NormalizedLookup,
	type NormalizedWriteInput,
	type SecretMetadata,
	type SecretStore,
	SecretStoreError,
} from './secret-store-types.ts';

/**
 * Builds an in-memory secret store for tests and platforms without a Keychain.
 * @param options - Optional clock, id factory, and service-name overrides.
 * @returns A {@link SecretStore} backed by a private `Map`.
 */
export function createMockSecretStore({
	idFactory = randomUUID,
	now = () => new Date(),
	serviceName = 'mock.ensemblr.secret-store',
}: MockSecretStoreOptions = {}): SecretStore {
	const records = new Map<
		string,
		{ metadata: SecretMetadata; value: string }
	>();

	/** Retrieves the in-memory record for a normalised lookup. */
	function getRecord(lookup: NormalizedLookup) {
		return records.get(createIdentityKey(lookup));
	}

	/**
	 * Constructs a metadata object for an in-memory secret.
	 * @param input - Normalised write input.
	 * @param reference - Keychain identity pair (synthetic for the mock).
	 * @param timestamp - ISO timestamp.
	 * @param id - Explicit identifier (default generated by `idFactory`).
	 * @returns A {@link SecretMetadata} value.
	 */
	function createMetadata(
		input: NormalizedWriteInput,
		reference: KeychainReference,
		timestamp: string,
		id = idFactory(),
	): SecretMetadata {
		return {
			...reference,
			backend: 'mock',
			characterCount: input.value.length,
			createdAt: timestamp,
			displayName: input.displayName,
			id,
			key: input.key,
			maskedDisplay: maskSecret(input.value),
			metadata: input.metadata,
			scope: input.scope,
			scopeId: input.scopeId,
			updatedAt: timestamp,
		};
	}

	return {
		async create(input) {
			const normalized = normalizeWriteInput(input);
			const identityKey = createIdentityKey(normalized);

			if (records.has(identityKey)) {
				throw new SecretStoreError(
					'already-exists',
					`A secret metadata entry already exists for ${formatLookup(normalized)}.`,
				);
			}

			const timestamp = now().toISOString();
			const reference = createKeychainReference(serviceName, normalized);
			const metadata = createMetadata(normalized, reference, timestamp);
			records.set(identityKey, { metadata, value: normalized.value });

			return metadata;
		},
		async delete(lookup) {
			records.delete(createIdentityKey(normalizeLookup(lookup)));
		},
		async listMetadata(filter) {
			const normalizedFilter = normalizeFilter(filter);
			const metadata = Array.from(
				records.values(),
				(record) => record.metadata,
			);

			return filterMetadata(metadata, normalizedFilter);
		},
		maskSecret,
		async read(lookup) {
			return getRecord(normalizeLookup(lookup))?.value ?? null;
		},
		async update(input) {
			const normalized = normalizeWriteInput(input);
			const identityKey = createIdentityKey(normalized);
			const existing = records.get(identityKey);

			if (!existing) {
				throw new SecretStoreError(
					'not-found',
					`No secret metadata entry exists for ${formatLookup(normalized)}.`,
				);
			}

			const timestamp = now().toISOString();
			const metadata = createMetadata(
				normalized,
				existing.metadata,
				timestamp,
				existing.metadata.id,
			);

			records.set(identityKey, {
				metadata: {
					...metadata,
					createdAt: existing.metadata.createdAt,
				},
				value: normalized.value,
			});

			return records.get(identityKey)?.metadata ?? metadata;
		},
	};
}
